<?php
/*
*
* Language file for Help Desk Software HESK (https://www.hesk.com)
* Language: Türkçe (Turkish)
* Version: 2.8.x
*
* ==> CONTRIBUTORS
*
* Levent Özberk (http://www.leventozberk.com)
* Onur
* Ömer Faruk GÜL
* Ehliman ŞEN (@EhlimanSen)
*
* ==> HOW TO TRANSLATE THIS FILE
*
* https://www.hesk.com/knowledgebase/?article=34
*
* ==> HOW TO CUSTOMIZE TEXT
*
* Do NOT customize text inside here, it will be overwritten by updates!
*
* Follow this guide instead:
* https://www.hesk.com/knowledgebase/?article=88
*
* ==> IMPORTANT: FILE ENCODING
*
* This file *must* be saved in UTF-8 encoding without byte order mark (BOM)
* Test chars: àáâãäåæ
*
* https://www.hesk.com/knowledgebase/?article=87
*
*/

// Native name of language, for example: Deutsch
$hesklang['LANGUAGE']='Türkçe';

// English name of language, for example: German
$hesklang['LANGUAGE_EN']='Turkish';

// Language encoding. It MUST be set to UTF-8 for all languages!
$hesklang['ENCODING']='UTF-8';

// MySQL utf8 collation. Do not change if not sure what to use.
$hesklang['_COLLATE']='utf8_turkish_ci';

// This is the email break line that will be used in email piping
$hesklang['EMAIL_HR']='------ Bu satırın üstünü yanıtla ------';

// EMAIL SUBJECTS
$hesklang['new_ticket_staff']='[#%%TRACK_ID%%] Yeni talep: %%SUBJECT%%';
$hesklang['ticket_received']='Destek Talebiniz Alındı';
$hesklang['ticket_assigned_to_you']='Sana yeni talep atandı';
$hesklang['new_reply_by_customer']='[#%%TRACK_ID%%] Kullanıcı tarafından cevaplanan: %%SUBJECT%%';
$hesklang['new_reply_by_staff']='[#%%TRACK_ID%%] Görevli tarafından cevaplanan: %%SUBJECT%%';
$hesklang['category_moved']='[#%%TRACK_ID%%] Talep taşındı: %%SUBJECT%%';
$hesklang['new_note']='[#%%TRACK_ID%%] Not eklendi: %%SUBJECT%%';
$hesklang['new_pm']='Yeni özel mesaj: %%SUBJECT%%';
$hesklang['forgot_ticket_id']='Tüm taleplerin id numaraları';

// ERROR MESSAGES
$hesklang['cant_connect_db']='Veritabanına bağlanılamadı!';
$hesklang['invalid_action']='Geçersiz işlem';
$hesklang['select_username']='Lütfen kullanıcı adınızı seçiniz';
$hesklang['enter_pass']='Lütfen parolanızı giriniz';
$hesklang['cant_sql']='SQL sorgusu çalıştırılamıyor';
$hesklang['contact_webmsater']='Lütfen site yöneticisine haber veriniz';
$hesklang['mysql_said']='MySQL Diyor ki';
$hesklang['wrong_pass']='Hatalı parola.';
$hesklang['session_expired']='Oturumunuzun süresi bitmiş, lütfen aşağıdaki formdan tekrar giriş yapınız.';
$hesklang['attempt']='Geçersiz girişim!';
$hesklang['not_authorized_tickets']='Bu kategori içindeki talepleri görüntülemeye yetkili değilsiniz!';
$hesklang['must_be_admin']='Bu sayfayı görüntülemeye yetkili değilsiniz! Sayfayı görüntüleyebilmek için yönetici olarak giriş yapmalısınız.';
$hesklang['no_session']='Yeni oturum başlatılamadı!';
$hesklang['error']='Hata';
$hesklang['int_error']='Dahili kod hatası';
$hesklang['no_trackID']='Takip Numarası Bulunamadı';
$hesklang['status_not_valid']='Durum geçerli değil';
$hesklang['trackID_not_found']='Takip Numarası (ID) Bulunamadı';
$hesklang['enter_message']='Lütfen mesajınızı yazınız';
$hesklang['select_priority']='Lütfen bir önem derecesi seçiniz';
$hesklang['ticket_not_found']='Talep bulunamadı! Lütfen takip numarasını doğru yazdığınızdan emin olun!';
$hesklang['no_selected']='Talep seçilmedi, bir işlem yapılamadı';
$hesklang['id_not_valid']='Bu geçerli bir ID değildir.';
$hesklang['enter_id']='Lütfen takip numarasını yazınız';
$hesklang['enter_name']='Lütfen müşteri adını yazınız';
$hesklang['enter_date']='Lütfen aramak istediğiniz tarihi yazınız';
$hesklang['date_not_valid']='Bu tarih biçimi geçerli değil. Lütfen tarihi <b>GG-AA-YYYY</b> formatında yazınız.';
$hesklang['enter_subject']='Lütfen talep konusunu yazınız';
$hesklang['invalid_search']='Geçersiz arama işlemi';
$hesklang['choose_cat_ren']='Lütfen ismini değiştireceğiniz kategoriyi seçiniz';
$hesklang['cat_ren_name']='Lütfen yeni kategori adını yazınız';
$hesklang['cat_not_found']='Kategori bulunamadı';
$hesklang['enter_cat_name']='Lütfen kategori adını yazınız';
$hesklang['no_cat_id']='Kategori ID bulunamadı';
$hesklang['cant_del_default_cat']='Varsayılan kategoriyi silemezsiniz, sadece ismini değiştirebilirsiniz.';
$hesklang['no_valid_id']='Geçerli bir kullanıcı ID si değil';
$hesklang['user_not_found']='Kullanıcı bulunamadı';
$hesklang['enter_real_name']='Lütfen kullanıcının gerçek adını-soyadını giriniz';
$hesklang['enter_valid_email']='Lütfen geçerli bir e-posta adresi giriniz';
$hesklang['enter_username']='Lütfen kullanıcı adı giriniz (giriş için)';
$hesklang['asign_one_cat']='Lütfen kullanıcıya en az 1 kategori atayınız!';
$hesklang['signature_long']='İmza 1000 karakterden uzun olamaz.';
$hesklang['confirm_user_pass']='Lütfen parolayı doğrulayınız';
$hesklang['passwords_not_same']='Girilen 2 parola aynı değil!';
$hesklang['cant_del_admin']='Varsayılan yöneticiyi silemezsiniz!';
$hesklang['cant_del_own']='Oturumu açık olan profili silemezsiniz!';
$hesklang['enter_your_name']='Lütfen adınızı-soyadınızı yazınız';
$hesklang['sel_app_cat']='Lütfen atanacak kategoriyi seçiniz';
$hesklang['sel_app_priority']='Lütfen atanacak önem derecesini seçiniz';
$hesklang['enter_ticket_subject']='Lütfen talep konunuzu yazınız';
$hesklang['user_not_found_nothing_edit']='Kullanıcı bulunamadı, bir işlem yapılmadı';

// ADMIN PANEL
$hesklang['administrator']='Yönetici';
$hesklang['login']='Giriş Yap';
$hesklang['user']='Kullanıcı';
$hesklang['username']='Kullanıcı Adı';
$hesklang['pass']='Parola';
$hesklang['confirm_pass']='Parola Doğrulaması';
$hesklang['logged_out']='Çıkış Yap';
$hesklang['logout']='Çıkış';
$hesklang['logout_success']='Başarıyla Çıkış Yaptınız!';
$hesklang['click_login']='Giriş Yapmak İçin Buraya Tıklayınız';
$hesklang['back']='Geri Dön';
$hesklang['displaying_pages']='<b>%d</b> adet talep gösteriliyor. Sayfalar :';
$hesklang['trackID']='Takip Numarası (ID)';
$hesklang['timestamp']='Timestamp';
$hesklang['name']='Adı - Soyadı';
$hesklang['subject']='Konu';
$hesklang['status']='Durum';
$hesklang['priority']='Öncelik';
$hesklang['open']='Yeni';
$hesklang['open_action']='Talebi Aç'; // Open ACTION
$hesklang['close']='Kapalı'; // Closed ticket STATUS
$hesklang['any_status']='Tümü';
$hesklang['high']='Yüksek';
$hesklang['medium']='Orta';
$hesklang['low']='Düşük';
$hesklang['del_selected']='Seçilen talepleri sil';
$hesklang['manage_cat']='Kategori Yönetimi';
$hesklang['profile']='Profiliniz';
$hesklang['show_tickets']='Talepleri Göster';
$hesklang['sort_by']='Sırala';
$hesklang['date_posted']='Eklenme Tarihi';
$hesklang['category']='Kategori';
$hesklang['any_cat']='Tüm Kategoriler';
$hesklang['order']='Sıralama';
$hesklang['ascending']='Artan';
$hesklang['descending']='Azalan';
$hesklang['display']='Sayfalama';
$hesklang['tickets_page']='talep her sayfada';
$hesklang['find_ticket']='Talep Bul';
$hesklang['yyyy_mm_dd']='GG-AA-YYYY';
$hesklang['results_page']='sonuç her sayfada';
$hesklang['opened']='açıldı'; // The ticket has been OPENED
$hesklang['closed']='Çözülenler'; // Ticket has been RESOLVED
$hesklang['ticket']='Talep';
$hesklang['tickets']='Talepler';
$hesklang['ticket_been']='Bu talep';
$hesklang['view_ticket']='Talep Görünümü';
$hesklang['open_tickets']='Yanıtlanmamış Yardım Talepleri';
$hesklang['remove_statement']='   ';
$hesklang['click_info']='Daha fazla bilgi için buraya tıklayınız';
$hesklang['reply_added']='Cevap eklendi';
$hesklang['reply_submitted']='Cevap Kaydedildi';
$hesklang['ticket_marked']='Bu talep işaretlendi';
$hesklang['ticket_status']='Talep Durumu';
$hesklang['replies']='Cevaplar';
$hesklang['date']='Tarih';
$hesklang['email']='E-Posta Adresi';
$hesklang['ip']='IP';
$hesklang['message']='Mesaj';
$hesklang['add_reply']='Cevap Ekle';
$hesklang['close_this_ticket']='Bu talebi Çözüldü olarak işaretle';
$hesklang['change_priority']='Önem derecesini değiştir';
$hesklang['attach_sign']='İmza ekle';
$hesklang['profile_settings']='Profil Ayarları';
$hesklang['submit_reply']='Cevabı Ekle';
$hesklang['support_panel']='Destek Paneli';
$hesklang['ticket_trackID']='Talep Takip Numarası';
$hesklang['c2c']='Devam etmek için tıklayınız';
$hesklang['tickets_deleted']='Talep silindi';
$hesklang['num_tickets_deleted']='<b>%d</b> talepler silindi.';
$hesklang['confirm_del_cat']='Bu kategoriyi silmek istediğinizden emin misiniz?';
$hesklang['cat_intro']='Bu sayfada kategorilerinizi yönetebilirsiniz. Yardım taleplerinizi kategorilere ayırarak 
daha esnek ve kullanımı kolay bir destek sistemi oluşturabilirsiniz.';
$hesklang['cat_name']='Kategori Adı';
$hesklang['remove']='Sil';
$hesklang['add_cat']='Yeni Kategori Ekle';
$hesklang['max_chars']='Azami 40 karakter';
$hesklang['create_cat']='Kategoriyi Oluştur';
$hesklang['ren_cat']='Kategori İsimlendir';
$hesklang['to']=' <b>tarihine :</b> ';
$hesklang['cat_added']='Kategori eklendi';
$hesklang['cat_name_added']='%s adlı kategori başarıyla eklendi.';
$hesklang['cat_renamed']='Kategori isimlendirildi.';
$hesklang['cat_renamed_to']='Seçilen kategori başarıyla yeniden isimlendirildi';
$hesklang['cat_removed']='Kategori silindi.';
$hesklang['cat_removed_db']='Seçilen kategori başarıyla veritabanından silindi.';
$hesklang['sure_remove_user']='Bu kullanıcıyı silmek istediğinizden emin misiniz?';
$hesklang['manage_users']='Kullanıcı Yönetimi';
$hesklang['users_intro']='Bu bölümde yönetim paneline girip talepleri cevaplamasını istediğiniz kullanıcılarınızla ilgili yetkilendirmeleri yapabilirsiniz. Yöneticiler tüm kategorilerde veya yetkilendirdiğiniz kategorilerdeki talepleri görebilir, düzenleyebilir, verdiğiniz yetkilere göre işlerinizde size yardımcı olabilirler.';
$hesklang['yes']='Evet';
$hesklang['no']='Hayır';
$hesklang['edit']='Düzenle';
$hesklang['add_user']='Yeni Kullanıcı Ekleme';
$hesklang['req_marked_with']='İşaretli alanların doldurulması zorunludur';
$hesklang['real_name']='Gerçek Adı - Soyadı';
$hesklang['signature_max']='İmza (max 1000 karakter)';
$hesklang['sign_extra']='HTML koduna izin verilmemektedir. Linkler zaten tıklanabilir halde olacaktır.';
$hesklang['create_user']='Kullanıcıyı Oluştur';
$hesklang['editing_user']='Kullanıcı Düzenleme';
$hesklang['user_added']='Kullanıcı eklendi';
$hesklang['user_added_success']='Kullanıcı Adı : %s ve Parola : %s ile yeni bir kullanıcı oluşturuldu.';
$hesklang['profile_updated']='Profil güncellendi';
$hesklang['profile_updated_success']='Profiliniz başarıyla güncellendi';
$hesklang['user_removed']='Kullanıcı silindi';
$hesklang['sel_user_removed']='Seçilen kullanıcı başarıyla veritabanından silindi.';
$hesklang['profile_for']='Profil Kullanıcı Adı : ';
$hesklang['new_pass']='Yeni Parola';
$hesklang['update_profile']='Profili Güncelle';
$hesklang['notify_new_posts']='Kategorilerime yeni talep veya mesaj geldiğinde beni bilgilendir.';
$hesklang['view_profile']='Profili Göster';
$hesklang['new_ticket_submitted']='Yeni destek talebi kaydedildi.';
$hesklang['user_profile_updated_success']='Bu kullanıcının profili başarıyla güncellendi.';
$hesklang['printer_friendly']='Yazdırılabilir Sayfa';
$hesklang['end_ticket']='--- Talep Sonu ---';

// CUSTOMER INTERFACE
$hesklang['your_ticket_been']='Talebiniz';
$hesklang['view_your_ticket']='Talebinizi Görüntüleyin';
$hesklang['submit_ticket']='Bir Talep Aç';
$hesklang['sub_ticket']='Talebi Kaydet';
$hesklang['before_submit']='Lütfen talebinizi göndermeden önce aşağıdaki şartları yerine getirdiğinizden emin olunuz :';
$hesklang['all_info_in']='Tüm bilgi alanlarını doldurunuz...';
$hesklang['all_error_free']='Tüm bilgileri doğru ve eksiksiz olarak yazınız...';
$hesklang['we_have']='Güvenlik Gereği :';
$hesklang['recorded_ip']='numaralı IP Adresiniz kaydedilmiştir.';
$hesklang['recorded_time']='Formu gönderme tarih ve saati kaydedilmektedir.';
$hesklang['save_changes']='Değişiklikleri Kaydet';
$hesklang['reply_submitted_success']='Cevabınız bu talebe başarıyla kaydedildi.';
$hesklang['ticket_submitted']='Talep Kaydedildi';
$hesklang['ticket_submitted_success']='Talebiniz başarıyla kaydedildi! Takip Numaranız';
$hesklang['your_ticket']='Talebiniz';

// Added in version 0.94
$hesklang['check_updates']='Hesk in son versiyonunu kullandığınızdan emin misiniz?';
$hesklang['check4updates']='Güncelleme Kontrolü Yap';
$hesklang['wait_reply']='Cevap Bekliyor';
$hesklang['replied']='Cevaplandı';
$hesklang['last_replier']='Son Cevaplayan';
$hesklang['staff']='Yönetici';
$hesklang['customer']='Müşteri';
$hesklang['close_selected']='Seçilen talepleri Çözüldü olarak işaretle';
$hesklang['execute']='İşlemi Yap';
$hesklang['saved_replies']='Hazır Cevaplar';
$hesklang['manage_saved']='Hazır Cevaplar';
$hesklang['manage_intro']='Bu bölümde hazır mesajlarınızı ekleyebilir ve yönetebilirsiniz. Genellikle her müşteriye verilebilecek, sık kullanılan cevaplarınızı burada kaydedebilirsiniz. Birçok müşteriye aynı cevabı yazarak vakit kaybetmek yerine bu özellik sayesinde daha kısa zamanda daha çok kişiye destek verebilirsiniz.';
$hesklang['saved_title']='Başlık (Azami 50 karakter)';
$hesklang['no_saved']='Bir hazır mesajınız bulunmamaktadır.';
$hesklang['delete_saved']='Bu hazır cevabı silmek istediğinizden emin misiniz?';
$hesklang['new_saved']='Bir hazır cevap ekle veya düzenle';
$hesklang['canned_add']='Yeni bir hazır cevap oluştur';
$hesklang['canned_edit']='Seçilen hazır cevabı düzenle';
$hesklang['save_reply']='Hazır Cevabı Kaydet';
$hesklang['saved']='Cevabı Kaydedildi';
$hesklang['your_saved']='Hazır mesajınız ileride kullanılmak üzere kaydedildi.';
$hesklang['ent_saved_title']='Lütfen hazır cevap başlığını yazınız';
$hesklang['ent_saved_msg']='Lütfen hazır cevap mesajınızı yazınız.';
$hesklang['saved_removed']='Hazır cevap silindi.';
$hesklang['saved_rem_full']='Seçilen hazır cevap başarıyla veritabanından silindi.';
$hesklang['clip_alt']='Bu mesajda ekli dosya mevcut';
$hesklang['attachments']='Ekli Dosya';
$hesklang['fill_all']='Doldurulması Zorunlu Alanlar';
$hesklang['file_too_large']='%s dosyanızın boyutu çok büyük';
$hesklang['cannot_move_tmp']='Dosyayı Ek klasörüne taşıyamazsınız.';
$hesklang['created_on']='Kayıt Tarihi';
$hesklang['tickets_closed']='Talep kapatıldı';
$hesklang['num_tickets_closed']='<b>%d</b> talepler kapatıldı';
$hesklang['select_saved']='Bir hazır cevap seçiniz.';
$hesklang['select_empty']='Seç / Boş';
$hesklang['insert_special']='Özel Takı Ekle (müşteri bilgileri ile değiştirilecek)';
$hesklang['move_to_catgory']='Talebi taşı';
$hesklang['move']='Taşı';
$hesklang['moved']='Talep taşındı';
$hesklang['moved_to']='Bu talep yeni kategorisine başarıyla taşındı.';
$hesklang['url']='URL';
$hesklang['all_not_closed']='Kapatılanlar';
$hesklang['chg_all']='Tümünü Değiştir';
$hesklang['settings']='Ayarlar';
$hesklang['settings_intro']='Bu sayfadaki bölümler sayesinde Yardım Masası Yazılımınızı kolaylıkla ayarlayabilir ve rahatça yönetebilirsiniz. Tüm ayarlarda bulunulan bölüm hakkında daha fazla bilgi ve yardım almak için yanındaki Soru İşaretine tıklayabilir veya scripti innDirdiğiniz dosyada bulunan readme.htm adlı dosyaya bakabilirsiniz.';
$hesklang['all_req']='Tüm alanların doldurulması zorunludur!';
$hesklang['wbst_title']='Web Site Başlığı';
$hesklang['wbst_url']='Web Site Adresi';
$hesklang['email_wm']='Webmaster E-Posta Adresi';
$hesklang['max_listings']='Sayfalardaki Talep Sayısı';
$hesklang['print_size']='Yazdırma Yazı Tipi';
$hesklang['debug_mode']='Hata Ayıklama Kipi';
$hesklang['on']='Açık';
$hesklang['off']='Kapalı';
$hesklang['use_secimg']='Spam Koruması Resmi?';
$hesklang['secimg_no']='Mevcut değil';
$hesklang['attach_use']='Ekli Dosya Kullanımı';
$hesklang['attach_num']='Mesajdaki Ekli Dosya Sayısı';
$hesklang['attach_type']='İzin Verilen Dosya Türleri';
$hesklang['place_after']='Mesajdan Sonra';
$hesklang['place_before']='Mesajdan Önce';
$hesklang['custom_f']='Özel Alan';
$hesklang['custom_u']='Bu alanı kullan';
$hesklang['custom_n']='Alan Adı';
$hesklang['custom_l']='Azami Uzunluk (karakter)';
$hesklang['db_host']='Veritabanı Sunucusu';
$hesklang['db_name']='Veritabanı Adı';
$hesklang['db_user']='Veritabanı Kullanıcı Adı';
$hesklang['db_pass']='Veritabanı Parolası';
$hesklang['err_sname']='Lütfen web site başlığını yazınız';
$hesklang['err_surl']='Lütfen web site adresinizi yazınız. Adresi tam olarak yazmayı unutmayınız (http:// veya https:// ile başlamalı)';
$hesklang['err_wmmail']='Lütfen geçerli bir webmaster e-posta adresi yazınız.';
$hesklang['err_nomail']='Lütfen geçerli bir cevaplamayın e-posta adresi yazınız.';
$hesklang['err_htitle']='Lütfen destek masanızın başlığını yazınız.';
$hesklang['err_hurl']='Lütfen Hesk klasörünüzün adresini yazınız. Adresi tam olarak yazmayı unutmayınız (http:// veya https:// ile başlamalı)';
$hesklang['err_lang']='Lütfen Hesk dilini seçiniz.';
$hesklang['err_nolang']='Seçeceğiniz dil hesk klasöründeki dil klasörü içinde olmalıdır! Dil ayarı yapmadan önce dil dosyalarını yüklediğinizden emin olunuz.';
$hesklang['err_max']='Lütfen her sayfada gösterilecek azami talep sayısını yazınız.';
$hesklang['err_psize']='Lütfen yazdırma fontu boyutunu yazınız.';
$hesklang['err_dbhost']='Lütfen MySQL veritabanı sunucunuzu yazınız.';
$hesklang['err_dbname']='Lütfen MySQL veritabanı adını yazınız.';
$hesklang['err_dbuser']='Lütfen MySQL veritabanı kullanıcı adını yazınız.';
$hesklang['err_dbpass']='Lütfen MySQL veritabanı kullanıcı parolasını yazınız.';
$hesklang['err_dbconn']='Girilen bilgilerle MySQL veritabanına bağlanılamadı!';
$hesklang['err_dbsele']='MySQL veritabanı seçilemedi, lütfen veritabanı adını tekrar kontrol ediniz.';
$hesklang['err_custname']='Lütfen seçtiğiniz isteğe bağlı alan adını yazınız.';
$hesklang['err_openset']='<b>hesk_settings.inc.php</b> dosyası yazılmak için açılamadı. Lütfen bu dosyanın CHMOD değerinin 666 olduğundan emin olun (rw-rw-rw- şeklinde)';
$hesklang['set_saved']='Ayarlar Kaydedildi';
$hesklang['set_were_saved']='Ayarlarınız başarılı olarak kaydedildi';
$hesklang['sec_img']='Güvenlik Resmi';
$hesklang['sec_miss']='Lütfen güvenlik numarasını yazınız';
$hesklang['sec_wrng']='Hatalı güvenlik numarası';
$hesklang['submit_problems']='Lütfen geri dönüp gereken düzeltmeleri yapınız';
$hesklang['cat_order']='Kategori Sıralaması';
$hesklang['reply_order']='Hazır Cevap Sıralaması';
$hesklang['move_up']='Yukarı taşı';
$hesklang['move_dn']='Aşağı taşı';
$hesklang['cat_move_id']='Kategori ID eksik';
$hesklang['reply_move_id']='Eksik yanıt ID';
$hesklang['forgot_tid']='Takip Numaranızı Unuttuysanız Tıklayınız.';
$hesklang['tid_send']='Talep Takip Numaramı Gönder';
$hesklang['tid_not_found']='Bu e-posta adresi ile kayıtlı bir talep bulunamadı.';
$hesklang['tid_sent']='Takip Numaranız Gönderildi.';
$hesklang['tid_sent2']='Talebinizle ilgili detaylı bilgiler e-posta adresinize gönderildi.';
$hesklang['check_spambox']='E-Posta kutunuzun istenmeyen bölümüne bakmayı unutmayınız!';
$hesklang['reply_not_found']='Hazır Cevap bulunamadı';
$hesklang['exists']='Mevcut';
$hesklang['no_exists']='Mevcut Değil';
$hesklang['writable']='Yazılabilir';
$hesklang['not_writable']='Yazılabilir Değil';
$hesklang['disabled']='Kapalı';
$hesklang['e_settings']='Eğer ayarlar dosyası (hesk_settings.inc.php) yazılabilir durumda değilse yaptığınız ayar değişikliklerini kaydedemeyeceksiniz. Lütfen daha fazla bilgi için yardım dosyasını (readme.htm) okuyunuz! ';
$hesklang['e_attdir']='Eğer ekli dosyalar klasörünüz (attachments) yoksa veya CHMOD izinleri yazılabilir durumda değilse, mesajlara dosya eklenemeyecektir. Lütfen daha fazla bilgi için yardım dosyasını (readme.htm) okuyunuz!';
$hesklang['e_save_settings']='Ayarlarınız kaydedilemedi, çünkü <b>hesk_settings.inc.php</b> dosyanız yazılabilir durumda değil.';
$hesklang['e_attach']='Kapalı, çünkü <b>attachments</b> klasörünüzün chmod değeri yazılabilir durumda değil.';
$hesklang['go']='Git';

// Added in version 2.0
$hesklang['v']='HESK Versiyonu';
$hesklang['check_status']='Durum Kontrolü';
$hesklang['sub_support']='Bir Talep Ekle';
$hesklang['open_ticket']='Teknik Destek Bölümüne bir yardım talebi gönder.';
$hesklang['view_existing']='Mevcut Talepleri Görüntüle';
$hesklang['vet']='Daha önce kaydettiğiniz talebinizi görüntüleyin.';
$hesklang['enter_user']='Lütfen kullanıcı adınızı yazınız.';
$hesklang['remember_user']='Kullanıcı Adımı Hatırla';
$hesklang['wrong_user']='Hatalı kullanıcı adı';
$hesklang['no_permission']='Bu makalede çalışmaya yetkili değilsiniz, lütfen üyelik bilgileriniz ile giriş yapınız.';
$hesklang['tickets_on_pages']='<b>Toplam Talep Sayısı :</b> %d <b>Sayfa Sayısı :</b> %d'; // First %d is replaced with number of tickets, second %d with number of pages
$hesklang['jump_page']='Sayfaya Git :';
$hesklang['no_tickets_open']='Çözülmemiş bir talep kaydı bulunmamaktadır.';
$hesklang['no_tickets_crit']='Arama kriterlerinize uyan bir talep kaydı bulunmamaktadır.';
$hesklang['confirm_execute']='Devam etmek istiyor musunuz?';
$hesklang['legend']='Açıklamalar';
$hesklang['main_page']='Ana Sayfa';
$hesklang['menu_users']='Kullanıcılar';
$hesklang['menu_cat']='Kategoriler';
$hesklang['menu_profile']='Profil';
$hesklang['menu_kb']='Bilgi Bankası'; // Admin MENU item
$hesklang['kb_text']='Bilgi Bankası'; // Item visible to customers
$hesklang['viewkb']='Bilgi Bankası Kayıtlarını Gör';
$hesklang['kb']='Bilgi Bankası Yönetimi';
$hesklang['kb_intro']='Bilgi Bankası Bölümü ile sıkça karşılaştığınız soruların cevaplarını daha kolay bulabilmeniz için size yardımcı olacak bir bölümdür. Bilgi veya Yardım almak istediğiniz Bilgi Bankası Bölümü kategorisini ve alt kategorilerini gezerek, yardım talebi açıp bekleyerek kaybedeceğiniz zamanı diğer işleriniz için kullanarak bazı sorunlarınızın çözümünü kolayca bulabilirsiniz.'; // Description in ADMIN panel
$hesklang['kb_is']='Bilgi Bankası Bölümü, Sıkça Karşılaştığınız Soruların cevaplarını daha kolay bulabilmeniz için size yardımcı olacak bir bölümdür. Bilgi veya Yardım almak istediğiniz Bilgi Bankası Bölümü ve alt bölümlerini gezerek, yardım talebi açıp bekleyerek kaybedeceğiniz zamanı diğer işleriniz için kullanarak bazı sorunlarınızın çözümünü kolayca bulabilirsiniz.'; // Description for CUSTOMERS
$hesklang['new_kb_art']='Yeni Bilgi Bankası İçeriği Ekle';
$hesklang['kb_cat']='Kategori';
$hesklang['kb_subject']='Konu';
$hesklang['kb_content']='İçerik';
$hesklang['kb_type']='Tür';
$hesklang['kb_published']='Yayınlandı';
$hesklang['kb_published2']='Bu içerik Bilgi Bankasında herkes tarafından görünecektir.';
$hesklang['kb_private']='Özel';
$hesklang['kb_private2']='Özel içerik sadece sistem yönetimince yetki verilmiş kişilerce görüntülenir.';
$hesklang['kb_draft']='Taslak';
$hesklang['kb_draft2']='Bu içerik kaydedilir fakat hemen yayınlanmaz. İçeriği sadece yetkili kişilerin okumasını istiyorsanız<br>Bilgi Bankası yönetiminden gerekli ayarları yapabilirsiniz...';
$hesklang['kb_links']='<i><span class="notice"><b>Uyarı !</b></span><br />Lütfen &lt;head&gt; ve &lt;body&gt; html takılarını içeren bir kod YAZMAYINIZ!</i>';
$hesklang['kb_ehtml']='HTML Kodu halinde yazacağım (Geçerli (X)HTML kodları kullanın)';
$hesklang['kb_dhtml']='Düz Metin halinde yazacağım (linkler tıklanabilir hale getirilecektir.)';
$hesklang['kb_save']='İçeriği Kaydet';
$hesklang['kb_e_subj']='İçerik Konusunu Yazınız!';
$hesklang['kb_e_cont']='İçerik Metnini Yazınız!';
$hesklang['kb_art_added']='İçerik Eklendi.';
$hesklang['your_kb_added']='Yeni Bir Bilgi Bankası İçeriği Başarıyla Eklendi.';
$hesklang['kb_art_deleted']='İçerik Silindi';
$hesklang['your_kb_deleted']='Seçilen Bilgi Bankası İçeriği başarıyla silindi.';
$hesklang['kb_art_mod']='İçerik Düzenlendi';
$hesklang['your_kb_mod']='Yaptığınız değişiklikler seçtiğiniz içeriğe başarıyla kaydedildi.';
$hesklang['kb_cat_new']='Yeni Bilgi Bankası Alt Kategorisi Ekle.';
$hesklang['kb_cat_parent']='Ana Kategori';
$hesklang['kb_cat_sub']='Alt Kategoriler';
$hesklang['kb_cat_title']='Kategori Başlığı';
$hesklang['kb_cat_published']='Kategori Bilgi Bankasındaki herkes tarafından görüntülenebilir.';
$hesklang['kb_cat_private']='Kategori sadece yöneticiler tarafından okunabilir.';
$hesklang['kb_cat_add']='Kategor Ekle';
$hesklang['kb_cat_e_title']='Kategor Başlığını Yazınız!';
$hesklang['kb_cat_added']='Kategor Eklendi';
$hesklang['kb_cat_added2']='Bilgi Bankasına yeni bir kategori başarıyla eklendi.';
$hesklang['kb_cat_man']='Bilgi Bankası Kategori Yönetimi';
$hesklang['kb_cat_edit']='Kategori detaylarını düzenle';
$hesklang['kb_cat_inv']='Geçersiz Kategori';
$hesklang['kb_cat_art']='Bu Kategorideki İçerik';
$hesklang['kb_p_art']='+ İçerik';
$hesklang['kb_p_art2']='Seçilen kategoriye yeni bir içerik ekle.';
$hesklang['kb_add_art']='İçerik Ekle';
$hesklang['kb_p_cat']='+ Kategori';
$hesklang['kb_p_cat2']='Seçilen kategorinin içine bir alt kategori oluştur.';
$hesklang['kb_add_cat']='Kategori Ekle';
$hesklang['kb_p_man']='Yönet';
$hesklang['kb_p_man2']='Seçilen kategoriyi yönet (düzenle, sil, içerik yönetimi).';
$hesklang['kb_main']='Bilgi Bankası ana kategorisi silinemez veya taşınamaz.';
$hesklang['kb_no_art']='Bu kategoride henüz bir içerik mevcut değil.';
$hesklang['author']='Yazan';
$hesklang['views']='Gösterim Sayısı';
$hesklang['delete']='Sil';
$hesklang['rating']='Verilen Puan';
$hesklang['votes']='Oylar';
$hesklang['kb_rated']='İçerik Puanı %s/5.0';
$hesklang['kb_not_rated']='Henüz hiçbir puan verilmedi.';
$hesklang['del_art']='Seçilen içeriği silmek istediğinizden emin misiniz?';
$hesklang['kb_art_id']='Eksik veya geçersiz içerik numarası!';
$hesklang['kb_art_edit']='İçeriği Düzenle';
$hesklang['revhist']='Son Düzenleme Bilgileri :';
$hesklang['revision1']='<li class="smaller">%s | , %s</li> tarafından gönderildi'; // %s = date, user making change
$hesklang['revision2']='<li class="smaller">%s |, %s</li> tarafıdan değiştirildi.'; // %s = date, user making change
$hesklang['kb_order']='Sıralama';
$hesklang['kb_delcat']='Bu kategoriyi silmek istediğinizden emin misiniz?';
$hesklang['kb_cat_mod']='Kategori Düzenlendi.';
$hesklang['your_cat_mod']='Yaptığınız değişiklikler seçtiğiniz kategoriye başarıyla kaydedildi.';
$hesklang['kb_cat_del']='Bilgi Bankası Kategorisi Silindi.';
$hesklang['kb_cat_dlt']='Seçilen Bilgi Bankası kategorisi silindi.';
$hesklang['allowed_cat']='Kategoriler';
$hesklang['allow_feat']='Yetkileri';
$hesklang['can_view_tickets']='Talep Görüntüleme';
$hesklang['can_reply_tickets']='Talep Cevaplama';
$hesklang['can_assign_tickets']='Atanan Talepler';
$hesklang['can_del_tickets']='Talep Silme';
$hesklang['can_edit_tickets']='Talep Cevaplarını Düzenleme';
$hesklang['can_change_cat']='Talep Kategorisini Değiştir';
$hesklang['can_man_kb']='Bilgi Bankası Yönetimi';
$hesklang['can_man_users']='Kullanıcı Yönetimi';
$hesklang['can_man_cat']='Kategori Yönetimi';
$hesklang['can_man_canned']='Hazır Cevap Yönetimi';
$hesklang['can_man_settings']='Yardım Masası Ayarları Yönetimi';
$hesklang['can_del_notes']='Herhangi bir talep notunu silme';
$hesklang['dan']='Kullanıcılar sadece kendi taleplerini silebilirler, diğer kullanıcıların taleplerini de silebilmelerini isterseniz buradan yetkilendirmeniz yeterlidir.';
$hesklang['in_all_cat']='Sadece izin verilen kategorilerde';
$hesklang['admin_can']='(tüm özelliklere ve kategorilere yetkili)';
$hesklang['staff_can']='(belirlenen kategorilere ve işlemlere yetkili)';
$hesklang['asign_one_feat']='Lütfen bu kullanıcıya en az bir yetki veriniz!';
$hesklang['na_view_tickets']='Bu talebi görüntülemeye yetkili değilsiniz.';
$hesklang['support_notice']='Üzgünüz, bu bölüm sadece lisanslı HESK kullanıcısı olmanız halinde saklanabilir!';
$hesklang['rart']='Bu içerik sorununuzu çözmenizde yardımcı oldu mu?';
$hesklang['r']='Bu cevap sorununuzu çözmenizde yardımcı oldu mu?';
$hesklang['tyr']='Puan verdiğiniz için teşekkür ederiz.';
$hesklang['cw']='Pencereyi Kapat';
$hesklang['cw2']='Pencereyi Kapat ve Talebi Ekle';
$hesklang['rh']='Bulduğım içerik sorunumu <i>çözdü</i>';
$hesklang['rnh']='Bulduğum içerik sorunumu <i>çözemedi</i>';
$hesklang['ar']='Zaten puan verdiniz.';
$hesklang['rated']='Kullanıcı Puanı %s/5.0 (%s puan)';
$hesklang['not_rated']='Henüz hiçbir kullanıcı puan vermedi.';
$hesklang['rdis']='Puanlama Sistemi Kapalı.';
$hesklang['kbdis']='Bilgi Bankası Kapalı.';
$hesklang['kbpart']='Üzgünüz, bu içeriğe erişmek için yetkili değilsiniz.';
$hesklang['popart']='En Çok Okunan Bilgi Bankası İçeriği :';
$hesklang['latart']='Son Eklenen Bilgi Bankası İçeriği :';
$hesklang['m']='Makalelerin devamı';
$hesklang['ac']='Bu kategorideki içerik :';
$hesklang['noa']='Henüz İçerik Yok';
$hesklang['noac']='Bu kategoride henüz bir içerik mevcut değil.';
$hesklang['dta']='Eklenme Tarihi';
$hesklang['ad']='İçerik Detayları';
$hesklang['aid']='İçerik Numarası';
$hesklang['as']='Çözüm';
$hesklang['search']='Arama';
$hesklang['sr']='Arama Sonuçları';
$hesklang['nosr']='Eşleşen içerik bulunamadı. Aradığınız konuyu Bilgi Bankasına bakın veya yeni bir destek talebi gönderin.';
$hesklang['rv']='Gösterimi Sıfırla';
$hesklang['rr']='Oyları Sıfırla (puanları)';
$hesklang['opt']='Seçenekler';
$hesklang['delcat']='Kategoriyi Sil';
$hesklang['move1']='Kategori içeriğini ana kategoriye taşı.';
$hesklang['move2']='Bu kategorinin içeriğini de sil.';
$hesklang['sc']='Önerilen Bilgi Bankası İçeriği.';
$hesklang['not']='Talepler'; // Number of all tickets in category
$hesklang['graph']='Grafik';
$hesklang['lu']='Kullanıcı Listesi';
$hesklang['aclose']='Otomatik Talep Kapatma';
$hesklang['aclose2']='yönetici cevabından sonra belirtilen gün geçince kapansın.';
$hesklang['s_ucrt']='Talebi Yeniden Açma';
$hesklang['urate']='Cevap Puanlama';
$hesklang['hesk_url']='Yardım Masası Adresi';
$hesklang['hesk_title']='Yardım Masası Başlığı';
$hesklang['cid']='Takip Numarası';
$hesklang['tfor']='Tarih/Saat Gösterim Şekli';
$hesklang['prefix']='Tablo Öneki';
$hesklang['s_ekb']='Bilgi Bankasını Aktifleştir';
$hesklang['s_kbs']='Bilgi Bankası Aramaları';
$hesklang['s_kbr']='Bilgi Bankası Puanlamaları';
$hesklang['s_maxsr']='Azami Arama Sonucu';
$hesklang['s_suggest']='Bilgi Bankası İçeriğini Öner';
$hesklang['s_spop']='Popüler İçeriği Göster';
$hesklang['s_slat']='En Son İçeriği Göster';
$hesklang['s_onin']='içerik <a href="../" target="_blank">Yardım Masası Ana Sayfasında</a> gösterilsin.';
$hesklang['s_onkb']='içerik <a href="../knowledgebase.php" target="_blank">Bilgi Bankası Ana Sayfasında</a> gösterilsin.';
$hesklang['s_scol']='Satırdaki Kategori Sayısı';
$hesklang['s_ptxt']='İçerik Önizleme Uzunluğu';
$hesklang['s_psubart']='Alt Kategori İçeriği';
$hesklang['enable']='Açık';
$hesklang['s_type']='Tip';
$hesklang['custom_r']='Zorunlu';
$hesklang['custom_place']='Konum';
$hesklang['custom_use']='Özel Alanlar';
$hesklang['stf']='Metin Alanı';
$hesklang['stb']='Geniş Metin Kutusu';
$hesklang['srb']='Yuvarlak Seçim Kutusu';
$hesklang['ssb']='Seçim Kutusu';
$hesklang['db']='Veritabanı Ayarları';
$hesklang['hd']='Yardım Masası Ayarları';
$hesklang['gs']='Genel Ayarlar';
$hesklang['cwin']='Pencereyi Kapat';
$hesklang['defw']='Varsayılan Değer';
$hesklang['ok']='TAMAM';
$hesklang['ns']='Bu özel alan için istediğiniz değerleri girip, <b>TAMAM</b> butonuna basınız. Ayarlar sayfasında da <b>Değişiklikleri Kaydet</b> butonuna basarak işlemi kaydetmeyi unutmayınız!';
$hesklang['rows']='Satırlar (yükseklik)';
$hesklang['cols']='Kolonlar (genişlik)';
$hesklang['opt2']='Bu Radyo Butonu Özelliği için, her satıra bir seçenek giriniz. En az iki seçenek sunmanız gerekmektedir!';
$hesklang['opt3']='Bu Seçim Kutusu Özelliği için, her satıra bir seçenek giriniz (formunuzda müşterileriniz için seçenekler oluşturulacaktır). En az iki seçenek sunmanız gerekmektedir!';
$hesklang['atl2']='En az iki seçenek giriniz (her satıra bir adet)!';
$hesklang['notes']='Notlar';
$hesklang['addnote']='+ Not Ekle';
$hesklang['noteby']='Notu Yazan';
$hesklang['delnote']='Notu Sil';
$hesklang['noteerr']='Not zaten silinmiş veya hatalı işlem';
$hesklang['s']='Ekle';
$hesklang['nhid']='Not müşteriler tarafından görülemez!';
$hesklang['delt']='Bu mesajı sil';
$hesklang['edtt']='Mesajı Düzenle';
$hesklang['edt1']='Mesaj düzenlendi';
$hesklang['edt2']='Seçilen mesajdaki değişiklikler kaydedildi.';
$hesklang['dele']='Bu talebi sil';
$hesklang['repd']='Mesaj silindi';
$hesklang['repl']='Seçilen mesaj silindi.';
$hesklang['tickets_found']='Arama Sonuçları';
$hesklang['al']='Yönetim Paneli Linki';
$hesklang['ap']='Yönetim Paneline Git';
$hesklang['dap']='Yönetim Paneli linki <a href="../" target="_blank">Yardım Masası Ana Sayfası</a>nda gösterilsin mi?';
$hesklang['q_miss']='Lütfen Spam Önleme Sorusunun cevabını giriniz';
$hesklang['use_q']='Spam Önleme Sorusu';
$hesklang['q_q']='-&gt; Soru (HTML kodu <font class="success">kullanılabilir</font>)';
$hesklang['q_a']='-&gt; Cevap';
$hesklang['err_qask']='Spam Koruması Sorusunu Giriniz';
$hesklang['err_qans']='Spam Koruması Sorusunu Cevaplayınız';
$hesklang['genq']='Rastgele bir soru üret';

// Added in version 2.1
$hesklang['amo']='Başka ekle';
$hesklang['delatt']='Seçilen ekli dosya silinsin mi?';
$hesklang['kb_att_rem']='Seçtiğiniz ekli dosya silindi';
$hesklang['inv_att_id']='Geçersiz Ekli Dosya Numarası!';
$hesklang['scb']='Açılan Kutu';
$hesklang['opt4']='Bu Açılan Kutu özelliği için, her satıra bir seçenek giriniz. Müşterilerinizin çoklu seçim yapabilmesi için seçenekler oluşturulacaktır. En az iki seçenek sunmanız gerekmektedir!';
$hesklang['autologin']='Her ziyaretimde otomatik giriş yap';
$hesklang['just_user']='Sadece kullanıcı adımı hatırla';
$hesklang['nothx']='Hayır, teşekkürler';
$hesklang['pinfo']='Profil Bilgileri';
$hesklang['sig']='İmza';
$hesklang['pref']='Seçenekler';
$hesklang['aftrep']='Bir Talep Cevaplandığında';
$hesklang['showtic']='Cevapladığım talebi göster';
$hesklang['gomain']='Yönetim ana sayfasına dön';
$hesklang['shownext']='Cevaplamam için sonraki talebi aç (yeni talep yoksa yönetim ana sayfası açılsın)';
$hesklang['rssn']='İlgileneceğiniz sonraki talep gösteriliyor.';
$hesklang['mrep']='Mevcut mesajı değiştir';
$hesklang['madd']='en alta ekle';
$hesklang['priv']='* ile işaretlenmiş Özel kategorilerin içeriği sadece yöneticiler tarafından görüntülenebilir.';
$hesklang['inve']='Geçersiz e-popsta dosyası';
$hesklang['emfm']='E-Posta dosyası bulunamadı';
$hesklang['hesk_lang']='Varsayılan Dil';
$hesklang['s_mlang']='Çoklu Dil';
$hesklang['s_mlange']='Bu ayar açıldığında kullanıcılarınız, yardım masanıza, yüklü herhangi bir dil desteği ile ulaşabileceklerdir. Bu ayarı, sadece <u>tüm dillerde destek sağlayabiliyorsanız</u> kullanmalısınız!';
$hesklang['s_inl']='Dil Klasörünü Test Et';
$hesklang['s_inle']='Testing the language folder for valid languages. Only languages that pass all tests are properly installed.';
$hesklang['beta']='(TEST VERSIYON)';
$hesklang['maxpost']='Muhtemelen bu sunucunun kabul ettiğinden daha fazla veri göndermeyi denediniz.<br /><br />Lütfen formu daha küçük veya eksiz olarak göndermeyi deneyin.';
$hesklang['ta']='Tekrar Test Et';
$hesklang['alo']='Otomatik Girişe İzin Ver';
$hesklang['chol']='Tercih Edilen Dil';
$hesklang['mmdl']='Bu dili tercih edilen dil olarak ayarla';
$hesklang['warn']='UYARI';
$hesklang['dmod']='Hata Ayıklama Kipi Açıldı. Hata ayıklama kipini, HESK yüklendikten ve çalıştırıldıktan sonra, ayarlar sekmesi altından kapattığınızdan emin olunuz.';
$hesklang['kb_spar']='Kategori adı olarak aynı ismi kullanamazsınız!';
$hesklang['mysql_root']='MySQL parolanız boş, root kullanıcı ile giriş yapmak istediğinizden emin misiniz? Bu güvenlik riski oluşturabilir!';
$hesklang['chg']='Değiştir';
$hesklang['chpri']='Öncelik Değiştirildi';
$hesklang['chpri2']='Talebin önem derecesi %s olarak değiştirildi.';
$hesklang['selcan']='Lütfen düzenlemek istediğiniz hazır cevabı seçiniz.';
$hesklang['q_wrng']='SPAM Koruması Cevabını Hatalı Girdiniz';
$hesklang['cndupl']='Bu isimle bir kategori zaten mevcut. Lütfen başka bir kategori adı seçerek deneyiniz.';
$hesklang['wsel']='Aramak istediğiniz kategoriyi seçiniz.';

// Added in version 2.2
$hesklang['eto']='Geçersiz istek';
$hesklang['id']='ID';
$hesklang['geco']='Direk link oluştur';
$hesklang['genl']='Direk kategori linki';
$hesklang['genl2']='Seçilen kategorilerde bu linki kullan &quot;Talebi onayla&quot; form.';
$hesklang['ask']='Yardım ara:';
$hesklang['exa']='Örnekler';
$hesklang['small']='Küçük Kutu';
$hesklang['large']='Bütük Kutu';
$hesklang['cpri']='Müşteri önceliği';
$hesklang['owner']='Sahibi';
$hesklang['unas']='Atanılmamış';
$hesklang['assi']='Ata';
$hesklang['asst']='Şu kişiye ata';
$hesklang['asst2']='Bu talebi şuna ata';
$hesklang['asss']='Kendine ata';
$hesklang['asss2']='Bu talebi kendine ata';
$hesklang['can_assign_self']='Kendine talep atanabilsin mi';
$hesklang['can_assign_others']='Diğerlerine talep atanabilir mi';
$hesklang['can_run_reports']='Sahip olduğu raporları alabilir mi?';
$hesklang['can_view_ass_others']='Diğerlerine atanmış raporlar görüntülenebilsin mi';
$hesklang['unoa']='Seçilen kullanıcının bu kategoriye erişim hakkı yok';
$hesklang['tasi']='Kendine atandı';
$hesklang['tasy']='Bu talep sana atandı';
$hesklang['taso']='Bu talep seçilen kullanıcıya atandı';
$hesklang['tasy2']='Bana atandı';
$hesklang['taso2']='Diğer personele atandı';
$hesklang['nose']='Yeni sahip seç';
$hesklang['onasc']='Bu sahibin seçilen kategoriye erişim hakkı yok.';
$hesklang['tunasi']='Talep atanmadı';
$hesklang['tunasi2']='Talep sahipsiz ve yeniden atanmaya hazır';
$hesklang['note']='Not';
$hesklang['success']='Başarılı';
$hesklang['nyt']='Bu talebin atandığı kişi';
$hesklang['noch']='Hiç bir değişiklik yapılmadı';
$hesklang['orch']='Değiştirilen siparişleri göster';
$hesklang['rfm']='Gerekli bilgiler eksik:';
$hesklang['repl0']='Bu işlemi gerçekleştirebilmek için yeterli izniniz yok';
$hesklang['repl1']='Bu gönderi bulunamadı';
$hesklang['reports']='Raporlar';
$hesklang['reports_intro']='Bu rapor bölümü, raporları yönetmeyi ve seçilen aralıkta talep istatistiklerini görüntülemeyi sağlar.';
$hesklang['refi']='Formu temizle';
$hesklang['dich']='Değişiklikleri geri al';
$hesklang['dire']='Rapor görüntüle';
$hesklang['m1']='Ocak';
$hesklang['m2']='Şubat';
$hesklang['m3']='Mart';
$hesklang['m4']='Nisan';
$hesklang['m5']='Mayıs';
$hesklang['m6']='Haziran';
$hesklang['m7']='Temmuz';
$hesklang['m8']='Ağustos';
$hesklang['m9']='Eylül';
$hesklang['m10']='Ekim';
$hesklang['m11']='Kasım';
$hesklang['m12']='Aralık';
$hesklang['d1']='Pazartesi';
$hesklang['d2']='Salı';
$hesklang['d3']='Çarşamba';
$hesklang['d4']='Perşembe';
$hesklang['d5']='Cuma';
$hesklang['d6']='Cumartesi';
$hesklang['d0']='Pazar';
$hesklang['mo']='Pt';
$hesklang['tu']='Sa';
$hesklang['we']='Ça';
$hesklang['th']='Pe';
$hesklang['fr']='Cu';
$hesklang['sa']='Ct';
$hesklang['su']='Pa';
$hesklang['from']='Tarihinden';
$hesklang['cinv']='Geçersiz tarih';
$hesklang['cinv2']='Kabul edilen format aa/gg/yyyy';
$hesklang['cinm']='Geçersiz ay değeri';
$hesklang['cinm2']='İzin verilen aralık';
$hesklang['cind']='Ay için geçersiz gün değeri';
$hesklang['cind2']='Seçilen ayın kabul edilebilir aralığı';
$hesklang['month']='Ay';
$hesklang['ocal']='Takvimi aç';
$hesklang['ca01']='Geçen sene';
$hesklang['ca02']='Geçen ay';
$hesklang['ca03']='Gelecek ay';
$hesklang['ca04']='Gelecek sene';
$hesklang['ca05']='Takvimi kapat';
$hesklang['cdr']='Tarih aralığını seç:';
$hesklang['crt']='Rapor türü';
$hesklang['r1']='Bugün';
$hesklang['r2']='Dün';
$hesklang['r3']='Bu ay';
$hesklang['r4']='Son ay';
$hesklang['r5']='Son 30 gün';
$hesklang['r6']='Bu hafta (Pts-Paz)';
$hesklang['r7']='Son hafta (Pts-Paz)';
$hesklang['r8']='Bu iş haftası (Ptz-Cu)';
$hesklang['r9']='Son iş haftası (Ptz-Cu)';
$hesklang['r10']='Bu yıl';
$hesklang['r11']='Son yıl';
$hesklang['r12']='Tüm zamanlar';
$hesklang['datetofrom']='&quot;Bu tarihten&quot; bundan yüksek olamaz &quot;Bu tarihe&quot;. Tarihler yer değiştirildi.';
$hesklang['t1']='Güne göre talepler';
$hesklang['t2']='Aya göre talepler';
$hesklang['t3']='Kullanıcıya göre talepler';
$hesklang['t4']='Kategoriye göre talepler';
$hesklang['ticass']='Atanmış talepler';
$hesklang['ticall']='Cevaplanan talepler';
$hesklang['totals']='Toplam';
$hesklang['all']='Hepsi';
$hesklang['atik']='Yeni talepler';
$hesklang['kbca']='Bununla aynı bilgi bankası kategorisine zaten sahipsin.';
$hesklang['menu_msg']='E-Posta';
$hesklang['menu_can']='Önceden hazırlanmış';
$hesklang['m_from']='Kimden:'; // Mail "from" address
$hesklang['m_to']='Kime:'; // Mail "to" address
$hesklang['m_sub']='Konu:'; // Mail subject
$hesklang['m_re']='Cvp:'; // Mail reply subject prefix, like "Re: Original subject"
$hesklang['m_fwd']='İlt:'; // Mail forward subject prefix, like "Fwd: Original subject"
$hesklang['m_h']='Özel mesajlar';
$hesklang['m_intro']='Hesk ile diğer üye personellere hızlı mesaj göndermek iin özel mesajları kullanın.';
$hesklang['e_udel']='(Kullanıcı silindi)';
$hesklang['new_mail']='Yeni özel mesaj';
$hesklang['m_send']='Mesaj gönder';
$hesklang['m_rec']='Mesaj alıcısı seç';
$hesklang['m_inr']='Geçersiz mesaj alıcısı';
$hesklang['m_esu']='Özel mesaj konusu girin';
$hesklang['m_pms']='Özel mesaj gönderildi';
$hesklang['inbox']='GELEN';
$hesklang['outbox']='GİDEN';
$hesklang['m_new']='YENİ MESAJ';
$hesklang['pg']='Sayfa göster';
$hesklang['npm']='Bu klasörde özel mesaj bulunamadı.';
$hesklang['m_ena']='Bu mesajı okumak için gerekli izniniz yok.';
$hesklang['mau']='Okunmadı olarak işaretle';
$hesklang['mo1']='Seçilen mesajı okundu olarak işaretle';
$hesklang['mo2']='Seçilen mesajı okunmadı olarak işaretle';
$hesklang['mo3']='Seçilen mesajı sil';
$hesklang['delm']='Bu mesajı sil';
$hesklang['e_tid']='Tekil talep ID oluşturma hatası, formu daha sonra göndermeyi deneyin.';
$hesklang['smmr']='Seçilen mesajlar okundu olarak işaretlendi';
$hesklang['smmu']='Seçilen mesajlar okunmadı olarak işaretlendi';
$hesklang['smdl']='Seçilen mesajlar silindi';
$hesklang['show']='Göster';
$hesklang['s_my']='Bana atananlar';
$hesklang['s_ot']='Diğer kişilere atananlar';
$hesklang['s_un']='Atanmayan talepler';
$hesklang['s_for']='Şunun için ara';
$hesklang['s_in']='Şunun içinde ara';
$hesklang['s_incl']='Şununla ara';
$hesklang['find_ticket_by']='Talep bul';
$hesklang['e_nose']='Atama durumu seçilmedi, tüm talepler gösteriliyor.';
$hesklang['fsq']='Arama sorgusu girin';
$hesklang['topen']='Açık';
$hesklang['nms']='Seçilen mesaj yok, değişiklik yapılmadı';
$hesklang['tlo']='Talebi kilitle';
$hesklang['tul']='Talebi aç';
$hesklang['loc']='Kilitlendi';
$hesklang['isloc']='Kilitli talepler çözüldü olarak işaretlenirse, müşteriler kilitli talepleri cevaplayamaz veya yeniden açamaz.';
$hesklang['tlock']='Talep kilitlendi';
$hesklang['tunlock']='Talep açıldı';
$hesklang['tislock']='Talep kilitlendi, müşteri bir daha cevaplayamaz.';
$hesklang['tislock2']='Bu talep kilitli, cevaplayamazsınız.';
$hesklang['nsfo']='İlgili makale bulunamadı.';
$hesklang['thist1']='<li class="smaller">%s | Talep, %s kategorisine, %s tarafından taşındı.</li>'; // %s = date, new category, user making change
$hesklang['thist2']='<li class="smaller">%s | Talep, %s kullanıcısına atandı. %s</li>'; // %s = date, assigned user, user making change
$hesklang['thist3']='<li class="smaller">%s | Talep, %s tarafından kapandı.</li>'; // %s = date, user making change
$hesklang['thist4']='<li class="smaller">%s | Talep, %s tarafından açıldı.</li>'; // %s = date, user making change
$hesklang['thist5']='<li class="smaller">%s | Talep, %s tarafından kilitlendi.</li>'; // %s = date, user making change
$hesklang['thist6']='<li class="smaller">%s | Talep, kilidi %s tarafından kaldırıldı.</li>'; // %s = date, user making change
$hesklang['thist7']='<li class="smaller">%s | Talep, %s tarafından oluşturuldu</li>'; // %s = date, user making change
$hesklang['elocked']='Bu  talep kilitlendi veya silindi.';
$hesklang['nti']='+ Yeni talep';
$hesklang['nti2']='Yeni talep ekle';
$hesklang['nti3']='Müşteri adına yeni talep oluşturmak için bu formu kullanın. Forma <i>Müşteri</i> bilgilerini girin (cmüşteri adı, müşteri e-postası, ...) kendi adınızı yazmayın! Talep müşteri tarafından açılmış gibi oluşturulacak.';
$hesklang['addop']='Seçenekler';
$hesklang['seno']='Müşteriye e-posta hatırlatmalarını gönder';
$hesklang['otas']='Gönderdikten sonra talebi göster';
$hesklang['notn']='Hatırlatmalar';
$hesklang['nomw']='Yardım masasının e-posta hatırlatması gönderme şekli:';
$hesklang['nwts']='Yeni bir talep sahibi ile teslim edildiğinde:';
$hesklang['ncrt']='Müşteri sahibi ile talebe cevap verdiğinde:';
$hesklang['ntam']='Talep bana atandığında';
$hesklang['npms']='Bana özel mesaj geldiğinde';
$hesklang['support_remove']='  ';
$hesklang['ycvtao']='Diğerlerine atanmış talepleri görüntüleme iznine sahip değilsiniz';
$hesklang['password_not_valid']='Şifre en azından 5 karekter uzunluğundan olmalı';
$hesklang['lkbs']='Bilgi bankası tavsiyeleri yükleniyor ...';
$hesklang['auto']='(Otamatik bir şekilde)';

// Added in version 2.3
$hesklang['unknown']='Bilinmeyen';
$hesklang['pcer']='Takibeden hataları düzeltin:';
$hesklang['seqid']='Talep numarası';
$hesklang['close_action']='Çözüldü olarak işaretle'; // Close ACTION
$hesklang['archived']='Etiketle';
$hesklang['archived2']='Etiketli talep';
$hesklang['add_archive']='Bu talebi etiketle';
$hesklang['add_archive_quick']='Seçilen talepleri etiketle';
$hesklang['remove_archive']='Bu talebin etiketini kaldır';
$hesklang['remove_archive_quick']='Seçilen taleplerin etiketini kaldır';
$hesklang['added_archive']='Etiketli talep';
$hesklang['removed_archive']='Etiketli olmayan talep';
$hesklang['added2archive']='Talep etiketlendi';
$hesklang['removedfromarchive']='Talep etiketi kaldırıldı';
$hesklang['num_tickets_tag']='<b>%d</b> talep etiketlendi';
$hesklang['num_tickets_untag']='<b>%d</b> talebin etiketi kaldırıldı';
$hesklang['can_add_archive']='Talepler etiketlenebilsin mi';
$hesklang['disp_only_archived']='Sadece etiketli talepler';
$hesklang['search_only_archived']='Sadece etiketli talepler';
$hesklang['critical']=' * Ciddi * ';
$hesklang['thist8']='<li class="smaller">%s | Talep önceliği %s olarak, %s tarafından değiştirildi</li>'; // %s = date,new priority, user making change
$hesklang['thist9']='<li class="smaller">%s | Talep durumu %s olarak, %s tarafından değiştirildi.</li>'; // %s = date, new status, user making change
$hesklang['thist10']='<li class="smaller">%s | Talep, otomatik olarak  %s atandı.</li>'; // %s = date, user making change
$hesklang['thist11']='<li class="smaller">%s | E-Mail piping ile gönderildi</li>'; // %s = date, user making change
// START abbreviatons used in "last updated" column
$hesklang['abbr']['year']='y';
$hesklang['abbr']['month']='ay';
$hesklang['abbr']['week']='h';
$hesklang['abbr']['day']='g';
$hesklang['abbr']['hour']='s';
$hesklang['abbr']['minute']='d';
$hesklang['abbr']['second']='sn';
// END abberviations
$hesklang['cnsm']='Mesaj gönderilememesinin nedeni:';
$hesklang['yhbb']='Başarısız giriş denemelerinden sonra sistem tarafından %s dakika yasaklandınız.';
$hesklang['pwdst']='Parola Güvenliği';
$hesklang['tid_mail']='Endişelenmeyin! <b>E-posta</b> adresini girin ve size Takip Numaranızı gönderelim:';
$hesklang['rem_email']='E-posta adresimi hatırla';
$hesklang['eytid']='Talep Takip Numaranızı giriniz.';
$hesklang['enmdb']='Girdiğiniz e-posta adresi bu talep id\'si için veritabanında eşleşmemiştir.';
$hesklang['confemail']='E-posta doğrula';
$hesklang['confemail2']='Lütfen e-posta adresini doğrulayın';
$hesklang['confemaile']='İki e-posta adresi aynı değil';
$hesklang['taso3']='Atandı:';
$hesklang['sec_enter']='Aşağıdaki resimde gördüğünüz sayıları giriniz.';
$hesklang['reload']='Resmi yeniden yükle';
$hesklang['verify_q']='SPAM Engelleme:'; // For anti-spam question
$hesklang['verify_i']='SPAM Engelleme:'; // For anti-spam image (captcha)
$hesklang['admin_login']='Personel girişi';
$hesklang['vrfy']='Test geçildi';
$hesklang['last_update']='Güncellendi';
$hesklang['cot']='Üstteki ciddi talepleri zorlama';
$hesklang['def']='Bunu varsayılan görünümüm yap';
$hesklang['gbou']='Bu talepler <b>Atanmamış</b>:';
$hesklang['gbom']='Bu taleplar <b>bana</b> atandı:';
$hesklang['gboo']='Talepler <b>%s</b> atandı:';
$hesklang['select']=' - - Seçmek için tıklayınız - - ';
$hesklang['chngstatus']='Durumu olarak güncelle';
$hesklang['perat']='Tüm taleplerin %s'; // Will change to "23% of all tickets"
$hesklang['viewart']='Bu makaleyi görüntüle';
$hesklang['chdp']='Lütfen varsayılan şifrenizi <a href="profile.php">Profile</a> sayfasından güncelleyiniz!';
$hesklang['chdp2']='Varsayılan olarak kullandığınız şifrenizi değiştiriniz!';
$hesklang['security']='Güvenlik';
$hesklang['kb_i_art']='Yeni makale';
$hesklang['kb_i_art2']='Makale ekle';
$hesklang['kb_i_cat']='Yeni kategori';
$hesklang['kb_i_cat2']='Yeni kategori ekle';
$hesklang['gopr']='Bilgi bankasını görüntüle';
$hesklang['kbstruct']='Bilgi bankası yapısı';
$hesklang['cancel']='İptal';
$hesklang['sh']='Mesajı gizle';
$hesklang['goodkb']='İyi bir bilgi bankası makalesi nasıl yazılır?';
$hesklang['catset']='Kategori ayarları';
$hesklang['inpr']='Yeni öncelik seç';
$hesklang['incat']='Yeni kategori seç';
$hesklang['instat']='Yeni durum seç';
$hesklang['tsst']='Talep durumu %s olarak ayarlandı';
$hesklang['aass']='Otamatik ata';
$hesklang['aaon']='Talep otamatik atama aktif (Pasif yapmak için tıklayınız)';
$hesklang['aaoff']='Talep otamatik atama devre dışı (aktif etmek için tıklayınız)';
$hesklang['uaaon']='Otamatik atama seçilen kullanıcı için aktif';
$hesklang['uaaoff']='Otamatik atama seçilen kullanıcı için devre dışı';
$hesklang['taasy']='Bu talep otamatik olarak sana atandı';
$hesklang['can_view_unassigned']='Atanamamış talepler görüntülenebilir mi';
$hesklang['ycovtay']='Sadece sana atanan talepleri görüntüleyebilirsin';
$hesklang['in_progress']='İşleniyor';
$hesklang['on_hold']='Bekletiliyor';
$hesklang['import_kb']='Bu talebi bilgi bankası makalesi olarak koy';
$hesklang['import']='<i>Özel talebi</i> <i>herkese açık makale</i> olarak eklemek üzeresiniz.<br /><br />Gizli bilgileri makaleden silip silmediğinize emin olun!';
$hesklang['tab_1']='Genel';
$hesklang['tab_2']='Yardım Masası';
$hesklang['tab_3']='Bilgi Masası';
$hesklang['tab_4']='Kişisel Alanlar';
$hesklang['tab_5']='E-posta - Piping';
$hesklang['disable']='Pasif';
$hesklang['dat']='Tarih &amp; Zaman';
$hesklang['lgs']='Dil';
$hesklang['onc']='Açık - Müşteriler';
$hesklang['ons']='Açık - Hepsi';
$hesklang['viewvtic']='Talepleri görüntüle';
$hesklang['reqetv']='Bu talebi görüntlülemek için e-posta gereklidir';
$hesklang['banlim']='Başarısız giriş deneme limiti';
$hesklang['banmin']='Yasaklama zamanı (dakika)';
$hesklang['subnot']='Bildiriyi gönder';
$hesklang['subnot2']='Talep gönderen müşterilere bildiri gönder';
$hesklang['eseqid']='Sıralı ID\'ler';
$hesklang['sconfe']='E-posta\'yı doğrula';
$hesklang['saass']='Otomatik atanan talepler';
$hesklang['swyse']='WYSIWYG Editörü';
$hesklang['hrts']='HESK\'i derecelendir';
$hesklang['hrts2']='Yönetim panelinde bu kodlamanın derecelendirme linkini göster';
$hesklang['emlpipe']='E-posta\'dan Talep Açma (Piping)';
$hesklang['emlsend']='E-posta gönderimi';
$hesklang['emlsend2']='E-posta gönderim şekli';
$hesklang['phpmail']='PHP posta';
$hesklang['smtp']='SMTP Sunucusu';
$hesklang['smtph']='SMTP Hostu';
$hesklang['smtpp']='SMTP Portu';
$hesklang['smtpu']='SMTP Kullanıcı Adı';
$hesklang['smtpw']='SMTP Şifresi';
$hesklang['smtpt']='SMTP Zamanı Aşımı';
$hesklang['other']='Diğer';
$hesklang['features']='Özellikler';
$hesklang['can_view_online']='Çevrimiçi personeller görüntülenebilsin mi';
$hesklang['online']='Çevrimiçi';
$hesklang['offline']='Çevrimdışı';
$hesklang['onlinep']='Çevrimiçi Kullanıcılar'; // For display in footer
$hesklang['sonline']='Çevrimiçi Kullanıcılar'; // For settings page
$hesklang['sonline2']='Çevrimiçi kişileri göster. Limit (dakika):'; // For settings page
$hesklang['gb']='İle grupla';
$hesklang['dg']='Gruplama';
$hesklang['err_dpi']='%s veritabanı %s önceki ile tüm HESH tabloları içermez, değişiklikler kaydedilemedi.';
$hesklang['err_dpi2']='Tablolar bulunamadı:';
$hesklang['sme']='SMTP hatası';
$hesklang['scl']='SMTP bağlantı günlüğü';
$hesklang['dnl']='İndir';
$hesklang['dela']='Bu eklentiyi sil';
$hesklang['pda']='Bu eklentiyi kalıcı bir şekilde silmek istiyor musunuz?';
$hesklang['thist12']='<li class="smaller">%s | Dosya eki %s  %s tarafından sildindi</li>'; // %s = date, deleted attachment, user making change
$hesklang['mopt']='Ayrıntılı ayarlar';
$hesklang['lopt']='Temel ayarlar';
$hesklang['meml']='Çoklu e-posta\'lar';
$hesklang['meml2']='Müşterilerin çoklu e-posta eklemesine izin ver.';

// Added in version 2.4
$hesklang['catd']='(kategori silindi)';
$hesklang['noopen']='Bu mail adresi için açılmış bir talep bulunamadı.';
$hesklang['maxopen']='Açabileceğiniz maksimum talep sayısına ulaştınız (%d of %d). Lütfen açık talepleriniz çözülünceye kadar bekleyiniz.';
$hesklang['ntnote']='Görevlendirildiğim bir talebe birisi not ekledi.';
$hesklang['cat_public']='Bu kategori herkese açıktır (gizlemek için tıklayınız)';
$hesklang['cat_private']='Bu kategori gizlidir (herkese açmak için tıklayınız)';
$hesklang['cat_aa']='Bu kategorideki talepleri otomatik görevlendir.';
$hesklang['cat_type']='Bu kategoriyi özel yap (yalnızca yöneticiler tarafından seçilebilir).';
$hesklang['caaon']='Seçilen kategori için otomatik görevlendirme aktifleştirildi.';
$hesklang['caaoff']='Seçilen kategori için otomatik görevlendirme devre dışı bırakıldı.';
$hesklang['cpub']='Kategori türü Genel olarak değiştirildi.';
$hesklang['cpriv']='Kategori türü Özel olarak değiştirildi.';
$hesklang['cpric']='Yalnızca yöneticiler özel kategoriyi seçebilirler, kullanıcıların bu hakkı yoktur.Kullanıcılar özel kategorileri seçemezler.';
$hesklang['user_aa']='Talepleri bu kullanıcıya otomatik olarak görevlendir.';
$hesklang['attach_size']='Maksmimum dosya boyutu';
$hesklang['B']='B';
$hesklang['kB']='kB';
$hesklang['MB']='MB';
$hesklang['GB']='GB';
$hesklang['bytes']='bytes';
$hesklang['kilobytes']='kilobytes';
$hesklang['megabytes']='megabytes';
$hesklang['gigabytes']='gigabytes';
$hesklang['smtpssl']='SSL Protokol';
$hesklang['smtptls']='TLS Protokol';
$hesklang['oo']='Unutulan Talep Numarası';
$hesklang['ool']='&quot;Unutulan talep numarası&quot; ile yalnızca açık talepleri listele';
$hesklang['mop']='Maksimum açık talep sayısı';
$hesklang['rord']='İş emrini yanıtla';
$hesklang['newbot']='En yeni yanıt en altta';
$hesklang['newtop']='En yeni yanıt en üstte';
$hesklang['ford']='Formu yanıtla';
$hesklang['formbot']='Formu en altta göster';
$hesklang['formtop']='Formu en üstte göster';
$hesklang['mysqlv']='MySQL versiyon';
$hesklang['phpv']='PHP versiyon';
$hesklang['csrt']='Geçerli HESK zamanı:';
$hesklang['listp']='Özel makaleleri listele';
$hesklang['listd']='Taslaktaki makaleleri listele';
$hesklang['artp']='Özel makaleler';
$hesklang['artd']='Taslak makaleler';
$hesklang['kb_no_part']='Bilgi bankasında hiç özel makale yok';
$hesklang['kb_no_dart']='Bilgi bankasında hiç taslak makale yok.';
$hesklang['attpri']='Bu dosyayı eklemeye yetkiniz yok.';
$hesklang['can_merge_tickets']='Talepleri birleştir';
$hesklang['mer_selected']='Seçili talepleri birleştir';
$hesklang['merged']='Seçili talepler tek bir talepte birleştirildi.';
$hesklang['merge_err']='Talepler birleştirilirken hata oluştu:';
$hesklang['merr1']='En az iki talep seçiniz.';
$hesklang['merr2']='Hedef talep bulunamadı.';
$hesklang['merr3']='Talebin bulunduğu kategoride işlem yapma yetkiniz bulunmuyor.';
$hesklang['tme']='%s talebi, bu talep ile birleştirildi: (%s).';
$hesklang['tme1']='%s talebi %s talebi ile birleştirildi.';
$hesklang['tme2']='%s talebine erişmek için bağlantılı E-Posta adresinizi giriniz.';
$hesklang['eyou']='Ayarlarınızı değiştirmek için, profil sayfanızı kullanınız.';
$hesklang['npea']='Bu kullanıcıyı düzenlemek için yetkiniz yok.';
$hesklang['duplicate_user']='Bu kullanıcı ile kayıtlı bir kullanıcı bulunmaktadır, lütfen başka bir kullanıcı adı seçiniz.';
$hesklang['kw']='Anahtarkelime';
$hesklang['kw1']='(opsiyonel - yeni satır, virgül ya da boşluk ile ayırınız)';
$hesklang['type_not_allowed']='<b>%s</b> uzantılı çalıştırılabilir dosyalar kabul edilmez. (%s)'; // %s changed to extension and file name: files ending with .exe are not accepted (test.exe)
$hesklang['unread']='Kullanıcı henüz bu yanıtı okumadı';
$hesklang['sticky']='Bu makaleyi &quot;iliştir&quot;';
$hesklang['stickyon']='Makaleyi &quot;İlişmiş&quot; olarak değiştir';
$hesklang['stickyoff']='Makaleyi &quot;Normal&quot; olarak değiştir';
$hesklang['ason']='Makale &quot;İlişmiş&quot; olarak işaretlendi';
$hesklang['asoff']='Makale &quot;Normal&quot; olarak işaretlendi';
$hesklang['ts']='Çalışılan süre';
$hesklang['start']='Başla / Durdur';
$hesklang['reset']='Sıfırla';
$hesklang['save']='Kaydet';
$hesklang['hh']='Saat';
$hesklang['mm']='Dakila';
$hesklang['ss']='Saniye';
$hesklang['thist']='Talep geçmişi';
$hesklang['thist13']='<li class="smaller">%s | Talep, %s ile by %s tarafından birleştirildi.</li>'; // %s = date, merged ticket ID, user making change
$hesklang['thist14']='<li class="smaller">%s | talep üzerinde çalışma süresi %s olarak %s</li> tarafından değiştirildi'; // %s = date, new time worked, user making change
$hesklang['thist15']='<li class="smaller">%s | Talep, %s tarafından gönderildi.</li>'; // %s = date, user making change
$hesklang['thist16']='<li class="smaller">%s | Talep POP3 Fetching ile alındı.</li>';
$hesklang['twu']='Talep üzerinde çalışılma süresi güncellendi.';
$hesklang['autoss']='Talep açıldığında, çalışma süresini otomatik başlat.';
$hesklang['ful']='Dosya yükleme limiti';
$hesklang['ufl']='Yükleyebileceğiniz dosya uzantıları:';
$hesklang['nat']='Eklenebilecek maksimum dosya sayısı:';
$hesklang['mfs']='Eklenebilecek maksimum dosya boyutu:';
$hesklang['lps']='Dil terihiniz kaydedildi';
$hesklang['sav']='Makale Görüntülenme Sayısı';
$hesklang['sad']='Makale Tarihi Görünümü';
$hesklang['emp']='Php sunucunuzun mysql desteği yoktur (mysqli eklentisi aktif olmalıdır)';
$hesklang['epd']='[HESK] EMAIL Piping devre dışı bırakıldı.';
$hesklang['pfd']='[HESK] POP3 Fetching devre dışı bırakıldı.';
$hesklang['pem']='[Mail ile alınan talep]'; // Default subject of piped tickets without subject
$hesklang['pde']='[Kullanıcı]'; // Default customer name for piped tickets without name
$hesklang['tab_6']='Çeşitli';
$hesklang['pop3']='POP3 Fetching';
$hesklang['pop3h']='POP3 Host';
$hesklang['pop3p']='POP3 Port';
$hesklang['pop3tls']='TLS Protokol';
$hesklang['pop3u']='POP3 Kullanıcı Adı';
$hesklang['pop3w']='POP3 Parola';
$hesklang['pop3e']='POP3 hatası';
$hesklang['pop3log']='POP3 bağlantı geçmişi';
$hesklang['mysqltest']='MySQL bağlantısını kontrol et';
$hesklang['smtptest']='SMTP bağlantısını kontrol et';
$hesklang['pop3test']='POP3 bağlantısını kontrol et';
$hesklang['contest']='Bağlantı kontrol ediliyor, bu işlem zaman alabilir.';
$hesklang['conok']='Bağlantı başarılı!';
$hesklang['conokn']='However, if your server requires username and password email will not be sent!';
$hesklang['saving']='Ayarlar kaydedliliyor, lütfen bekleyiniz.';
$hesklang['sns']='Ayarlar kaydedildi fakat, bazı özellikle testin başarısız olmasından ötürü bazı özellikler devre dışı bırakıldı.';
$hesklang['loops']='Döngüsel Mail';
$hesklang['looph']='Döngüsel Kontrol Adet';
$hesklang['loopt']='Döngüsel Zaman Dilimi(sn)';
$hesklang['didum']='Bunu mu demek istediniz? %s?'; // %s changes to email; did you mean someone@example.com?
$hesklang['yfix']='Evet, düzelt';
$hesklang['nole']='Hayır, düzeltme';
$hesklang['sconfe2']='Talep formu üzerinde &quot;e-posta onayı&quot; alanını göster';
$hesklang['oln']='Eski isim:';
$hesklang['nen']='Yeni isim:';
$hesklang['use_form_below']='<i>Talep isteği için bu formu kullanınız. Zorunlu alanlar işaretlenmiştir.</i>';
$hesklang['esf']='Bilgilendirme E-Postası gönderilemedi.';
$hesklang['qrr']='(alıntılı yanıt silindi)';
$hesklang['remqr']='Mail alıntılarını silmek';
$hesklang['remqr2']='Kullanıcı e-postasından gelen alıntıları sil.';
$hesklang['suge']='E-Posta Yazım Hatası Tespiti';
$hesklang['epro']='E_Posta Sağlayıcısı';
$hesklang['email_noreply']='No-Reply E-Posta Adresi';
$hesklang['email_name']='Posta Gönderici Adı';
$hesklang['vscl']='Yönetim tarafından belirlenen dosya boyutu limiti.';
$hesklang['fnuscphp']='Dosya yükleme iptal edildi, daha küçük bir dosya eklemeyi deneyiniz.';
$hesklang['redv']='Geçerli görünümü sıfırla';
$hesklang['fatte1']='Dosya ekleme ayarlarınız &quot;Gönderi başına&quot; kabul edilen dosya boyutu sınırından fazla.';
$hesklang['fatte2']='Eklediğiniz dosya boyutu, sunucunuzun kabul ettiği dosya boyutu sınırını aştı.';
$hesklang['fatte3']='Sunucunuz bu kadar büyük dosya boyutuna izin vermiyor, dosya yükleme üst sınırını yükseltiniz.';
$hesklang['embed']='Gömülü dosyalar';
$hesklang['embed2']='Gömülü dosyaları dosya eki olarak kaydet';
$hesklang['emrem']='(imaj silindi)';
$hesklang['hdemo']='(HIDDEN IN DEMO)';
$hesklang['ddemo']='Özür dileriz, bu özellik DEMO modda kullanılabilir değildir.';
$hesklang['sdemo']='Değişiklikleri kaydetme DEMO modunda devre dışı bırakılmştır.';
$hesklang['hud']='HESK güncel';
$hesklang['hnw']='Güncelleme mevcut';
$hesklang['getup']='HESK\'i güncelle';
$hesklang['updates']='Güncellemeler';
$hesklang['updates2']='HESK güncellemelerini otomatik denetle.';

// Added in version 2.5.0
$hesklang['attdel']='Bu dosya sunucudan silinmiştir. Mevcut değildir';
$hesklang['dsen']='Bu cevabı e-posta ile kullanıcıya gönderme.';
$hesklang['attrem']='* Some attached files have been removed *';
$hesklang['attnum']='Maksimum sayıya ulaşıldı: %s'; // %s will show attachment name
$hesklang['attsiz']='Dosya çok büyük: %s'; // %s will show attachment name
$hesklang['atttyp']='Dosya tipi izin verilenler listesinde değil: %s'; // %s will show attachment name
$hesklang['adf']='Admin klasörü';
$hesklang['atf']='Ek klasörü';
$hesklang['err_adf']='Seçilen Admin kasörü (%s) mevcut değil!'; // %s will show folder name
$hesklang['err_atf']='Seçilen ek klasörü (%s) mevcut değil!'; // %s will show folder name
$hesklang['err_atr']='Seçilen ek klasörü (%s) yazılabilir değil!'; // %s will show folder name
$hesklang['fatt']='Bu mesaja eklenen dosyalar:';
$hesklang['wrepo']='Talebi tekrar açarken lütfen cevap yazınız.';
$hesklang['ktool']='&raquo; Bilgibankası araçları';
$hesklang['uac']='Kategorideki başlık sayısını doğrula ve güncelle.';
$hesklang['acv']='Başlık sayısı doğrulandı.';
$hesklang['xyz']='Kategorideki genel, özel ve taslak başlık sayısı.';
$hesklang['reports_tab']='Rapor Alma'; // Tab title
$hesklang['can_run_reports_full']='Tüm raporları alabilir mi?';
$hesklang['can_export']='Talepleri dışarıya aktarabilir mi?';
$hesklang['roo']='<i>(yalnızca size aktarılmış talepleri rapora ekleyebilirsiniz.)</i>';
$hesklang['shu']='Link kısaltma';
$hesklang['export']='Talebi dışarı aktarma'; // Tab title
$hesklang['export_btn']='Talepleri dışarı aktar'; // Button title
$hesklang['export_intro']='Bu ayar, dışlarıya aktarılan taleplerin XML özet tablosuna aktarılarak Excel ile açılmasını sağlar.';
$hesklang['stte']='Dışarı aktarmak istediğiniz talepleri seçin';
$hesklang['dtrg']='Tarih aralığı';
$hesklang['sequentially']='Sıralı olarak'; // Order tickets: Sequentially
$hesklang['ede']='Cannot create export directory, please manually create a folder called <b>export</b> inside your attachments folder and make sure it is writable by PHP (on Linux CHMOD it to 777 - rwxrwxrwx).';
$hesklang['eef']='Rapor dosyası oluşturulamadı, aktarılacak dizinde yazma yetkiniz yok.';
$hesklang['inite']='Dışarıya aktarma başlatılıyor.';
$hesklang['gXML']='XML dosyası oluşturuluyor.';
$hesklang['nrow']='Dışarıya aktarılan talep sayısı: %d'; // %d will show number of rows exported
$hesklang['cZIP']='Dosya Zip dosyasına sıkıştırılıyor';
$hesklang['eZIP']='Zip arşivi oluşturulurken hata oluştu';
$hesklang['fZIP']='Dosya sıkıştırması tamamlandı';
$hesklang['pmem']='Ulaşılan bellek seviyesi: %.2f Mb'; // %.2f will be replaced with number of Mb used
$hesklang['ch2d']='&raquo; XML raporunu indirmek için tıklayın &laquo;';
$hesklang['n2ex']='İstediğiniz kriterde talep bulunamadı, aktarılacak bir talep yok.';
$hesklang['sp']='SPAM Önleme'; // For settings page
$hesklang['sit']='-&gt; İmaj türü';
$hesklang['sis']='Basit resim';
$hesklang['rcpb']='Site Anahtarı (Public key)';
$hesklang['rcpv']='Gizli Anahtar (Private key)';
$hesklang['pop3keep']='Kopyasını sakla';

// --> Text used by ReCaptcha
$hesklang['recaptcha_error']='SPAM önleyici cevap doğru değil, lütfen tekrar deneyiniz.';

// Added in version 2.6.0
$hesklang['ticket_closed']='[#%%TRACK_ID%%] Talep Kapatıldı/Çözüldü';
$hesklang['ms01']='Ock';
$hesklang['ms02']='Şub';
$hesklang['ms03']='Mar';
$hesklang['ms04']='Nis';
$hesklang['ms05']='May';
$hesklang['ms06']='Haz';
$hesklang['ms07']='Tem';
$hesklang['ms08']='Ağs';
$hesklang['ms09']='Eyl';
$hesklang['ms10']='Ekm';
$hesklang['ms11']='Kas';
$hesklang['ms12']='Ara';
$hesklang['sdf']='Gönderme tarihi formatı';
$hesklang['lcf']='Güncelleme tarihi formatı';
$hesklang['lcf0']='Kısa tanımlayıcı';
$hesklang['lcf1']='Tarih ve saat';
$hesklang['lcf2']='HESK stili';
$hesklang['ticket_tpl']='Talep şablonları';
$hesklang['can_man_ticket_tpl']='Talep şablonlarını yönet'; // Permission title
$hesklang['ticket_tpl_man']='Şablonları Yönet'; // Page and link title
$hesklang['ticket_tpl_intro']='Admin panelinden taleplere hızlıca cevap vermek için talep şablonları oluşturun veya düzenleyiniz.';
$hesklang['no_ticket_tpl']='Talep Şablonu Bulunmamaktadır';
$hesklang['ticket_tpl_title']='Başlık';
$hesklang['delete_tpl']='Bu şablonları silmek istediğinize emin misiniz?';
$hesklang['new_ticket_tpl']='Talep şablonu Ekle veya Düzenle';
$hesklang['ticket_tpl_add']='Yeni talep şablonu oluştur';
$hesklang['ticket_tpl_edit']='Seçilen şablonu düzenle';
$hesklang['save_ticket_tpl']='Şablonu kaydet';
$hesklang['ticket_tpl_saved']='Şablonunuz ileride kullanılmak üzere kaydedilmiştir';
$hesklang['ticket_tpl_removed']='Seçilen şablon veritabanından silinmiştir';
$hesklang['ticket_tpl_not_found']='Şablon bulunamadı.';
$hesklang['sel_ticket_tpl']='Düzeltmek istediğiniz talep şablonunu seçiniz';
$hesklang['ent_ticket_tpl_title']='Lütfen şablon başlığı giriniz';
$hesklang['ent_ticket_tpl_msg']='Lütfen şablon içeriği giriniz';
$hesklang['ticket_tpl_id']='Şablon ID si bulunamadı';
$hesklang['select_ticket_tpl']='Bir şablon seçiniz';
$hesklang['list_tickets_cat']='Bu kategorideki talepleri listeleyiniz';
$hesklang['def_msg']='[İleti Yok]';
$hesklang['emlreqmsg']='Bir ileti gereklidir.';
$hesklang['emlreqmsg2']='Mesajsız iletileri reddet';
$hesklang['relart']='İlgili Makaleler'; // Title of related articles box
$hesklang['s_relart']='İlgili makaleler'; // On settings page
$hesklang['tab_7']='Talep listesi';
$hesklang['fitl']='Talep listesi alanları';
$hesklang['submitted']='Eklendi';
$hesklang['clickemail']='Görüntüle';
$hesklang['set_pri_to']='Öncelik ayarı:'; // Action below the ticket list
$hesklang['pri_set_to']='Önecelik ayarı değiştirilmiştir -->:';
$hesklang['cat_pri']='Müşterilere öncelik ekleme izni verilmediğinde, öncelik kategori önceliği bazında olacaktır.';
$hesklang['cat_pri_info']='Müşterilere öncelik izni verilirse kategori önceliği devre dışı kalacaktır.<br /><br />Eğer müşteri önceliğine önem veriyorsanız ayarlar panelinden ayarı değiştirebilirsiniz:';
$hesklang['def_pri']='Kategori Önceliği:';
$hesklang['ch_cat_pri']='Kategori önceliğini ayarla';
$hesklang['cat_pri_ch']='Kategori önceliği ayarlandı -->:';
$hesklang['err_dbversion']='MySQL versiyonu eski:';
$hesklang['ip_whois']='IP whois';
$hesklang['ednote']='Notu düzenleme mesajı';
$hesklang['ednote2']='Not kayıt mesajı';
$hesklang['perm_deny']='Erişim reddedildi';
$hesklang['mis_note']='Not ID bulunamadı';
$hesklang['no_note']='Bu ID ye air not bulunamadı';
$hesklang['sacl']='Kaydet ve sonra devam et';
$hesklang['reply_saved']='Cevap mesajınız sonra gönderilmek üzere kaydedildi.';
$hesklang['submit_as']='Şu şekilde Kabul Et -->:';
$hesklang['sasc']='Müşteri mesajı şeklinde Onayla';
$hesklang['creb']='Müşteri cevabını şu kişi değiştirdi -->:';
$hesklang['show_select']='Göster &quot;Tıkla ve Seç&quot; varsayılan';
// Settings
$hesklang['mms']='Bakım modu';
$hesklang['mmd']='Bakım modunu aktifleştir';
// Customer notice
$hesklang['mm1']='Bakım modu devam ediyor.';
$hesklang['mm2']='Zamanlanmış bakım çalışması için Yardım Masamız geçici olarak kapatılmıştır.';
$hesklang['mm3']='Verdiğimiz rahatsızlıktan ötürü özür dileriz. Lütfen daha sonra tekrar erişmeyi deneyiniz.';
// Staff notice
$hesklang['mma1']='Bakım Modu Aktif!';
$hesklang['mma2']='Müşteriler yardım masasını kullanamamaktadır.';
$hesklang['tools']='Araçlar';
$hesklang['banemail']='Banlanan E-Postalar';
$hesklang['banemail_intro']='Belirli e-posta adreslerinin talep açmasını önleyiniz.';
$hesklang['no_banemails']='<i>Hiçbir e-posta yasaklı değil.</i>';
$hesklang['eperm']='Kalıcı e-posta yasakları:';
$hesklang['bananemail']='E-posta adresi yasağı';
$hesklang['savebanemail']='Bu e-postayı yasakla';
$hesklang['enterbanemail']='Yasaklamak için bir e-posta adresi giriniz.';
$hesklang['validbanemail']='Lütfen e-posta adresini kurala uygun yazınız ÖR. (<i>john.doe@domain.com</i>) yada tüm domain ÖR. (<i>@domain.com</i>)';
$hesklang['email_banned']='<i>%s</i> adresi banlanmıştır. Panelde talep açamayacaktır.'; // %s will be replaced with email
$hesklang['emailbanexists']='<i>%s</i> adresi zaten banlanmış.'; // %s will be replaced with email
$hesklang['email_unbanned']='e-posta engeli kaldırıldı';
$hesklang['banby']='Engelleyen ';
$hesklang['delban']='Engeli sil';
$hesklang['delban_confirm']='Silmek istediğinize emin misiniz?';
$hesklang['baned_e']='Talep açma isteğiniz reddedilmiştir.';
$hesklang['baned_ip']='Yardım masası erişiminiz engellenmiştir.';
$hesklang['can_ban_emails']='E-posta yasaklama';
$hesklang['can_unban_emails']='E-posta yasak kaldırma (E-posta yasaklama aktif olmalı)';
$hesklang['eisban']='Bu e-posta adresi yasaklanmıştır.';
$hesklang['click_unban']='yasağı kaldırmak için tıklayınız.';
$hesklang['banip']='Yasaklanan IP Adresleri';
$hesklang['banip_intro']='Ip adresleri banlanan ziyaretçiler Yardım Masasına erişemez veya talep açamaz.';
$hesklang['ipperm']='Kalıcı IP Yasağı:';
$hesklang['iptemp']='Giriş Başarısızlığı Yasakları:';
$hesklang['savebanip']='IPyi Yasakla';
$hesklang['no_banips']='<i>Hiçbir IP yasaklanmadı.</i>';
$hesklang['bananip']='IP adresi yasağı';
$hesklang['banex']='Örnekler:';
$hesklang['iprange']='IP Aralığı';
$hesklang['ippermban']='IP yi kalıcı olarak yasakla';
$hesklang['enterbanip']='Yasaklamak için IP adresi veye aralığı giriniz.';
$hesklang['validbanip']='Uygun formatta IP adresi veya aralığı girmelisiniz';
$hesklang['ip_banned']='<i>%s</i> adresi yasaklanmıştır. Daha fazla talep açamayacaktır.'; // %s will be replaced with IP
$hesklang['ip_rbanned']='<i>%s</i> IP aralığı yasaklanmıştır. Daha fazla talep açamayacaktır.'; // %s will be replaced with IP
$hesklang['ipbanexists']=' <i>%s</i> adresi zaten yasaklı.'; // %s will be replaced with IP
$hesklang['iprbanexists']=' <i>%s</i> IP aralığı zaten yasaklı .'; // %s will be replaced with IP
$hesklang['ip_unbanned']='IP yasağı silindi';
$hesklang['ip_tempun']='Geçici IP yasağı silindi';
$hesklang['can_ban_ips']='IP yasaklayabilir.';
$hesklang['can_unban_ips']='IP yasak kaldırabilir (IP yasaklama aktif olmalı)';
$hesklang['ipisban']='Bu IP adresleri yasaklandı.';
$hesklang['m2e']='Sona erme süresi (dakika)';
$hesklang['info']='Bilgi';
$hesklang['sm_title']='Servis Mesajları';
$hesklang['sm_intro']='Bilinen bir problem hakkında önceden hazırlamış olduğunuz servis mesajlarını anında gönderin.';
$hesklang['can_service_msg']='Servis mesajlarını düzenle';
$hesklang['new_sm']='Yeni Servis mesajı';
$hesklang['edit_sm']='Servis mesajını düzenle';
$hesklang['ex_sm']='Varolan servis mesajı';
$hesklang['sm_author']='Yazar';
$hesklang['sm_type']='Tip';
$hesklang['sm_published']='Yayınlandı';
$hesklang['sm_draft']='Taslak';
$hesklang['sm_style']='Stil';
$hesklang['sm_none']='Yok';
$hesklang['sm_success']='Başarılı';
$hesklang['sm_info']='Bilgi';
$hesklang['sm_notice']='Not';
$hesklang['sm_error']='Hata';
$hesklang['sm_save']='Servis mesajını kaydet';
$hesklang['sm_preview']='Servis mesajını önizle';
$hesklang['sm_mtitle']='Başlık';
$hesklang['sm_msg']='Mesaj';
$hesklang['sm_e_title']='Servis mesajına başlık giriniz';
$hesklang['sm_e_msg']='Servis mesajını yazınız';
$hesklang['sm_e_id']='mesaj ID si bulunamadı';
$hesklang['sm_added']='Yeni bir servis mesajı eklendi';
$hesklang['sm_deleted']='Servis mesajı silindi';
$hesklang['sm_not_found']='Bu servis mesajı mevcut değil';
$hesklang['no_sm']='Servis mesajları yok';
$hesklang['del_sm']='Bu servis mesajı silinsin mi?';
$hesklang['sm_mdf']='Servis mesajı kaydedildi';
$hesklang['sska']='Önerilen makaleleri göster';
$hesklang['taws']='Bu makaleler önerilmiştir:';
$hesklang['defaults']='Varsayılanlar';
$hesklang['pncn']='Yeni talep formunda Müşteriye Bildir seçeneğini aktif et';
$hesklang['pncr']='Talep cevapla formunda Müşteriye Bildir seçeneğini aktif et';
$hesklang['pssy']='Müşterilene önerilen bilgi bankası makalelerini göster';
$hesklang['ccct']='Müşteri çözümü';
$hesklang['custnot']='Ne zaman müşteriye bildirim gönderilecek';
$hesklang['notnew']='Bir yeni destek talebi oluşturuldu';
$hesklang['notclo']='Bir destek talebi Çözümlendi olarak işaretlendi.';
$hesklang['enn']='E-posta konusunda varsa görmezden gel --->:';
$hesklang['spamn']='SPAM notice';
$hesklang['spam_inbox']='<span style="color:red"><b>Email doğrulaması yok?</b><br />Size bir doğrulama e-postası gönderik. Gelen kutunuzda bulamıyorsanız lütfen Spam kutunuzu da kontrol ediniz. <b>SPAM değildir</b> olarak işaretlerseniz gelecekte bizden gelen mailler gelen kutunuza düşecektir.</span>';
$hesklang['ekb_n']='<b>Hayır</b>, Bilgi bankasını pasifleştir.';
$hesklang['ekb_y']='<b>Evet</b>, Bilgi bankasını aktifleştir.';
$hesklang['ekb_o']='<b>Evet</b>, Sadece bilgi bankası olarak kullan (<i>helpdesk modunu devre dışı bırakır</i>)';
$hesklang['kb_set']='Bilgi Bankası Ayarları';
$hesklang['kbo1']='Sadece Bilgi Bankası - Modu';
$hesklang['kbo2']='<br /><br />Ziyaretçiler destek talebinde bulunamazlar ve direkt olarak Bilgi Bankasına yönlendirilirler.';
$hesklang['fpass']='Şifreni mi unuttun?';
$hesklang['passr']='Şifreyi sıfırla';
$hesklang['passa']='E-posta yoluyla şifre sıfırlamaya izin ver';
$hesklang['passe']='E-posta adresini giriniz';
$hesklang['passs']='Şifre sıfırlama bağlantısını gönder';
$hesklang['noace']='Bu e-posta adresiyle kayıtlı bir hesap yoktur';
$hesklang['pemls']='Şifre sıfırlamanız için adresinize talimatları gönderdik';
$hesklang['reset_password']='Yardım Masası Şifre Sıfırlama Talebi'; // Email subject
$hesklang['ehash']='Bilinmeyen veya süresi geçmiş şifre sıfırlama bağlatısı.';
$hesklang['ehaip']='Şifre sadece sıfırlama talebi gönderilen IP üzerinden değiştirilebilir.';
$hesklang['resim']='<b>Yeni şifrenizi ayarlayınız!</b>';
$hesklang['permissions']='Yetkiler';
$hesklang['atype']='Hesap Tipi';
$hesklang['astaff']='Kadro';
$hesklang['oon1']='Bana sadece açık destek taleplerini gönder.';
$hesklang['oon2']='Bana tüm destek taleplerimi gönder.';
$hesklang['anyown']='Any owner';
$hesklang['pfr']='Başka bir POP3 üzerinden talep alımı devam etmektedir.';
$hesklang['pjt']='Görev Zamanaşımı';
$hesklang['pjt2']='dakika sonra başla';
$hesklang['nkba']='Bilgi Bankası aramasının düzgün çalışması için yeterli miktarda benzersiz makale gerekmektedir.<br /><br />Arama ve öneri sonuçlarını geliştirmek için Bilgi Bankanıza daha fazla makale eklemelisiniz.';
$hesklang['saa']='Sabitlenmiş makaleler, makale listesinin en başında gözükür.';
$hesklang['yhbr']='Bir talebe çok fazla sayıda cevap yazdınız. Yeni cevap için sisteminiz %s dakika boyunca kilitli kalacaktır.';
$hesklang['RECAPTCHA']='tr';

// Added in version 2.7.0
$hesklang['imap']='IMAP Alma';
$hesklang['imaph']='IMAP Host';
$hesklang['imapp']='IMAP Port';
$hesklang['enc']='Şifreleme';
$hesklang['ssl']='SSL';
$hesklang['tls']='TLS';
$hesklang['none']='Yok';
$hesklang['imapu']='IMAP Kullanıcı Adı';
$hesklang['imapw']='IMAP Şifre';
$hesklang['imaptest']='IMAP bağlantısını test et';
$hesklang['ifd']='[HESK] IMAP alma ayarlardan kapalı.';
$hesklang['iei']='[HESK] PHP IMAP eklentisi yüklü değil.';
$hesklang['ifr']='Başka bir IMAP alma görevi halen devam ediyor..';
$hesklang['arp']='Sayfayı otomatik olarak yeniden yükle';
$hesklang['arpp']='Her sayfada talep listesini otomatik olarak yeniden yükle:';
$hesklang['seconds']='saniye';
$hesklang['minutes']='dakika';
$hesklang['atbr']='Bu talep, yanıtlanmadan önce atanması gerekir.';
$hesklang['attm']='Bu talebi bana ata';
$hesklang['owneed']='Sahibi gerekli';
$hesklang['taat']='Bu talep zaten <b>%s</b> atandı.';
$hesklang['scoy']='Kendinize atamak istediğinizden emin misiniz?';
$hesklang['scot']='%s \'ye atamak istediğinizden emin misiniz?';
$hesklang['ycto']='Evet, sahibini Değiştir.';
$hesklang['ncto']='Hayır, şu anki sahibini koru.';
$hesklang['fass']='Sahibi gerekli';
$hesklang['req_sub']='Konu gerekli';
$hesklang['req_msg']='Mesaj gerekli';
$hesklang['req_email']='Email gerekli';
$hesklang['default_subject']='%s talep';
$hesklang['off-hide']='Müşteri formunda gizle';
$hesklang['not_valid_email']='Geçerli bir e-posta adresi girin veya bu alanı boş bırakın';
$hesklang['write_down']='<span style="color:red">Gelecekte başvurmak için Talep Kimliğinizi yazmanızı öneririz.</span>';
$hesklang['re_confirm1']='Bunu devre dışı bırakmak, "Güvenlik" altındaki "Talepleri görüntülemek için e-posta iste" özelliğini de devre dışı bırakır.. Devam mı?';
$hesklang['re_confirm2']='Bunu etkinleştirmek, "Özellikler" in altında "E-posta gerektir" özelliğini de etkinleştirir. Devam mı?';
$hesklang['can_email_tpl']='E-posta şablonlarını düzenle';
$hesklang['et_title']='E-posta Şablonları';
$hesklang['et_intro']='Personelinize ve müşterilerinize gönderilen e-postaları değiştirin';
$hesklang['file']='Dosya';
$hesklang['efile']='Dosya düzenleme';
$hesklang['rdesc']='(Alıcı) Açıklama';
$hesklang['desc_forgot_ticket_id']='(Müşteri) Talep takip kimliğini unuttum';
$hesklang['desc_new_reply_by_staff']='(Müşteri) Yeni personel yanıtı';
$hesklang['desc_new_ticket']='(Müşteri) Talep alındı';
$hesklang['desc_ticket_closed']='(Müşteri) Talep kapalı / çözüldü';
$hesklang['desc_category_moved']='(Personel) Talep yeni bir kategoriye taşındı';
$hesklang['desc_new_reply_by_customer']='(Personel) Yeni müşteri yanıtı';
$hesklang['desc_new_ticket_staff']='(Personel) Yeni talep gönderildi';
$hesklang['desc_ticket_assigned_to_you']='(Personel) Size bir talep atadı.';
$hesklang['desc_new_pm']='(Personel) Yeni özel mesaj';
$hesklang['desc_new_note']='(Personel) Size atanan talebe yeni not';
$hesklang['desc_reset_password']='(Staff) Reset your password';
$hesklang['etfm']='Bir veya daha fazla e-posta şablonu eksik.<br /><br />Tüm e-posta şablon dosyalarını <i>/language/%s/emails</i> klasörünüze yüklediğinizden emin olun.';
$hesklang['etfw']='Bazı e-posta şablonları yazılabilir değil.<br /><br />
                    PHP\'nin<i>/language/%s/emails</i> klasöründeki tüm dosyalara yazma izni olduğundan emin olun.<br /><br />
                    Unix sunucularında CHMOD değerinin 666 olması gerebilir. (rw-rw-rw-)';
$hesklang['et_e_id']='Eksik şablon kimliği';
$hesklang['et_fm']='Bu e-posta şablonu dosyası eksik';
$hesklang['et_fw']='Bu e-posta şablonu dosyası yazılabilir değil';
$hesklang['et_save']='E-posta şablonunu kaydet';
$hesklang['updated_on']='Tarihinde güncellendi';
$hesklang['ticket_url']='Talep URL\'si';
$hesklang['pm_url']='Özel mesaj URL\'si';
$hesklang['et_num']='Talep sayısı';
$hesklang['et_list']='Destek taleplerinin listesi';
$hesklang['et_empty']='E-posta şablonu boş olamaz';
$hesklang['et_saved']='E-posta şablonu kaydedildi';
$hesklang['source']='Kaynak';
$hesklang['select_category']='Bir kategori seç';
$hesklang['select_category_text']='Size nasıl yardımcı olabiliriz?';
$hesklang['select_category_staff']='Talep kategorisini seçin';
$hesklang['scat']='Kategori seçme sınırı';
$hesklang['scat2']='(kategori sayısı daha yüksekse bir seçim kutusu gösterilir)';
$hesklang['new_cf']='Yeni özel alan';
$hesklang['cf_intro']='Müşterilerden ek veri toplayabilmeniz için bir talep formu gönderene özel alanlar eklemek için bu özelliği kullanın.';
$hesklang['cf_public']='Genel';
$hesklang['cf_private']='Sadece personel';
$hesklang['cf_cust']='Müşteriler için';
$hesklang['cf_all']='Herşey';
$hesklang['cf_cat']='Seçili';
$hesklang['cf_ctrl']='İpucu: Birden fazla kategoriyi seçmek için CTRL tuşunu basılı tutun';
$hesklang['visibility']='Görünürlük';
$hesklang['cf_save']='Özel alanı kaydet';
$hesklang['ex_cf']='Etkin özel alanlar';
$hesklang['no_cf']='Etkin özel alan yok';
$hesklang['del_cf']='Bu özel alanı silinsin mi? Bu ayrıca kayıtlı herhangi bir özel alan verilerini veritabanından silecektir!';
$hesklang['cf_e_id']='Geçersiz kimlik';
$hesklang['edit_cf']='Özel alanı düzenle';
$hesklang['cf_deleted']='Özel alan silindi';
$hesklang['cf_not_found']='Bu özel alan mevcut değil';
$hesklang['cf_added']='Yeni bir özel alan eklendi';
$hesklang['cf_nocat']='Bu özel alan için en az bir kategori seçin';
$hesklang['cf_mdf']='Özel alan kaydedildi';
$hesklang['atl1']='En az bir seçenek girin.';
$hesklang['sch']='Gizli';
$hesklang['meml3']='Birden çok e-postanın girilmesine izin ver';
$hesklang['dmin']='Minimum kabul edilen tarih';
$hesklang['dmax']='Maksimum kabul tarihi';
$hesklang['d_day']='gün(ler)';
$hesklang['d_week']='hafta(lar)';
$hesklang['d_month']='ay(lar)';
$hesklang['d_year']='yıl(lar)';
$hesklang['d_any']='Herhangi bir tarih';
$hesklang['d_fixed']='Sabit tarih';
$hesklang['d_relative']='Göreli tarih';
$hesklang['d_mm']='Minimum tarih maksimum tarihten yüksek olamaz';
$hesklang['d_emin']='<i>%s</i> için Minimum tarih %s';
$hesklang['d_emax']='<i>%s</i> için Maksimum tarih%s';
$hesklang['d_format']='Tarih görüntüleme formatı';
$hesklang['d_custom']='Özel format';
$hesklang['d_ci']='Yalnızca gelişmiş kullanıcılar için: Geçerli bir PHP tarih biçimi, bkz.PHP El Kitabı.';
$hesklang['cf_noe']='<i>%s</i> alanına geçerli bir e-posta adresi girin';
$hesklang['cf_noem']='<i>%s</i> alanına bir veya daha fazla geçerli e-posta adresi girin';
$hesklang['cf_limit']='50 aktif özel alanınız var, yeni oluşturulamaz.';
$hesklang['can_resolve']='Talepleri çözebilir miyim?';
$hesklang['can_change_own_cat']='Talep kategorisini değiştir (izin verilir)';
$hesklang['can_submit_any_cat']='Herhangi bir kategoriye talep gönderebilirsiniz';
$hesklang['noauth_submit']='Bu kategoriye talep gönderme yetkiniz yok!';
$hesklang['noauth_move']='Bu kategoriye talep taşıma yetkiniz yok!';
$hesklang['noauth_resolve']='Talepleri çözme yetkiniz yok!';
$hesklang['force_ssl']='SSL bağlantılarını zorla';
$hesklang['d_ssl']='<i>devre dışı bırak</i> - bu seçeneği yönetmek için https:// ile bu sayfayı açın';
$hesklang['scno']='Bu durum değiştirilemez';
$hesklang['statuses']='Durumlar';
$hesklang['statuses_intro']='Yardım masanıza özel talep durumları eklemek için bu aracı kullanın';
$hesklang['color']='Renk';
$hesklang['csscl']='CSS sınıfı veya rengi';
$hesklang['clr_view']='Metin üzerinde renk önizlemesi';
$hesklang['cbc']='Müşteriler tarafından değiştirilebilir';
$hesklang['ccc']='Müşteriler bu durumu değiştirebilir mi?';
$hesklang['del_status']='Bu durumu sil?';
$hesklang['ex_status']='Mevcut durumlar';
$hesklang['status_hesk']='Dahili durumları (burada değiştirilemez)';
$hesklang['status_custom']='Özel Durumlar';
$hesklang['status_custom_none']='Özel durumlar yok. Bunları yukarıdaki formu kullanarak ekleyebilirsiniz.';
$hesklang['status_save']='Durumu Kaydet';
$hesklang['list_tkt_status']='Bu durumdaki tüm talepleri listeleyin';
$hesklang['new_status']='Yeni özel durum';
$hesklang['edit_status']='Özel durumu düzenle';
$hesklang['err_status']='Durum adını girin';
$hesklang['status_added']='Yeni bir özel durum eklendi';
$hesklang['status_e_id']='Geçersiz kimlik';
$hesklang['status_mdf']='Özel durum kaydedildi';
$hesklang['status_deleted']='Özel durum silindi';
$hesklang['status_not_found']='Bu özel durum mevcut değil';
$hesklang['status_not_empty']='Bu durum, bu duruma sahip talepler olduğu için kaldırılamaz';
$hesklang['status_limit']='100 özel durumunuz var, yeni oluşturulamaz.';
$hesklang['public_link']='Genel bağlantı';
$hesklang['frames']='Çerçeveler';
$hesklang['frames2']='Üçüncü taraf alanlarındaki çerçevelerde HESK yüklemesini engelle';
$hesklang['numsub']='Gönderilen talepler';
$hesklang['hidf']='Gizli girişler, Talep gönderme formunda müşteriler tarafından görünür değildir (genel olarak ayarlanmışsa, değer hala talep ayrıntıları sayfasında görünür olacaktır). Personel üyeleri için normal metin alanları gibi davranır.';
$hesklang['rcheck']='Varsayılan bir seçenek seçmeyin';
$hesklang['refresh_page']='Bu sayfayı yenile';
$hesklang['del_kba']='Bu makaleyi sil';
$hesklang['del_kbaa']='Bu makaleyi kalıcı olarak sil';
$hesklang['hni1']='HESK henüz yüklü değil mi?';
$hesklang['hni2']='Bu yardım masası düzgün yüklü ve henüz yapılandırılmamış gibi görünüyor.';
$hesklang['hni3']='HESK\'yi yüklemek için <a href="docs/">Dokümantasyondaki talimatlar</a> inceleyin';
$hesklang['cf']='Önbellek klasörü';
$hesklang['e_cdir']='Önbellek klasörü bulunmadığı ve yazılabilir olmadığı sürece, Hesk e-postaları veya önbellek sonuçlarını ayrıştıramaz.';
$hesklang['step1']='Adım 1';
$hesklang['step2']='Adım 2';
$hesklang['dffs']='İndirme tamamlandığında, dosyayı sunucudan silin';
$hesklang['fd']='Dışa aktarma dosyası sunucudan silindi';
$hesklang['TZ']='Saat dilimi';
$hesklang['thist17']='<li class="smaller">%s | submitted by IMAP fetching</li>';
$hesklang['sir3']='Görünmez reCAPTCHA';
$hesklang['invisible']='görünmez';
$hesklang['imap_not']='PHP, IMAP desteği ile derlenmiş değil';
$hesklang['imap_warning']='%1$s kullanıcı IMAP alma e-posta adresinizle aynı e-posta adresine sahip: %2$s'; // %1$s = username, %2$s = email address
$hesklang['pop3_warning']='%1$s kullanıcı POP3 e-posta adresinizle aynı e-posta adresine sahip: %2$s'; // %1$s = username, %2$s = email address
$hesklang['fetch_warning']='Bu, kullanıcı e-posta bildirimlerinden yeni taleplerin oluşturulduğu bir e-posta döngüsüyle sonuçlanabilir. Getirilen e-posta adresiniz benzersiz olmalı ve başka biri tarafından kullanılmamalıdır.';
$hesklang['from_warning']='Hesk, e-posta bildirimleri göndermek için bir SMTP sunucusu kullanıyor. Your &quot;%1$s&quot; on the &quot;%2$s&quot; tab should be set to: %3$s'; // %1$s = "From email" text, %2$s = "General" tab text, %3$s = email address
$hesklang['can_view_ass_by']='Başkalarına atanmış olan talepleri görebilirsiniz';
$hesklang['can_privacy']='Can anonymize tickets';
$hesklang['confirm_anony']='Bu talebi anonimleştir';
$hesklang['anon_selected']='Anonim seçilmiş talepler';
$hesklang['privacy_anon_info']='Taleplerden (müşteri adı, e-posta, mesaj, ek, IP ...) tüm kişisel tanımlanabilir verileri ve içeriği kaldırın, ancak istatistik için veritabanında talepleri (unutulma hakkı) saklayın.';
$hesklang['success_anon']='Talep başarıyla anonim hale getirildi';
$hesklang['num_tickets_anon']='Anonim taleplerin sayısı: <b>%d</b>';
$hesklang['anon_IP']='0.0.0.0'; // IP in anonymized tickets
$hesklang['anon_name']='[Müşteri]'; // Customer name in anonymized tickets
$hesklang['anon_email']=''; // Customer email in anonymized tickets
$hesklang['anon_subject']='[Konu]'; // Ticket subject of anonymized tickets
$hesklang['anon_message']='[Mesaj]'; // Ticket message in anonymized tickets
$hesklang['thist18']='<li class="smaller">%s | %s tarafından anonimleştirilmiş.</li>';
$hesklang['print_selected']='Seçilen talepleri yazdır';
$hesklang['with_selected']='Seçilen ile:';
$hesklang['assign_selected']='Seçilene ata:';
$hesklang['assign_no']='Sahibi seçilmedi, değişiklik yapılmadı';
$hesklang['assign_1']='Seçilen talepler atanmamış olarak ayarlandı.';
$hesklang['assign_2']='Ticket ID %1$s set to Unassigned'; // %1$s = ticket numerical ID
$hesklang['assign_3']='%1$s error: already assigned to %2$s'; // %1$s = ticket tracking ID, %2$s = owner name
$hesklang['assign_4']='%1$s assigned to %2$s'; // %1$s = ticket tracking ID, %2$s = owner name
$hesklang['assign_5']='%1$s error: %2$s doesn\'t have access to ticket category'; // %1$s = ticket tracking ID, %2$s = owner name
$hesklang['assign_log']='Bulk ticket assign result:<br /><br />Assigned: %1$s<br />Errors: %2$s<br /><br />Log:<br /><pre>%3$s</pre>'; // %1$s = number of tickets assigned, %2$s = number of errors, %3$s = log
$hesklang['IP_addr']='IP adresi';
$hesklang['moret']='Daha fazla seçenek'; // More options button title
$hesklang['btn_more']='Daha'; // More options button text
$hesklang['btn_print']='Yazdırma';
$hesklang['btn_edit']='Düzenle';
$hesklang['btn_lock']='Talebi kilitle';
$hesklang['btn_unlock']='Taleb kilidini aç';
$hesklang['btn_tag']='Talebi etiketle';
$hesklang['btn_resend']='E-posta bildirimini yeniden gönder';
$hesklang['btn_untag']='Taleb etiketi kaldır';
$hesklang['btn_import_kb']='Bilgi Bankasına Aktar';
$hesklang['btn_anony']='Anonim talep';
$hesklang['btn_delt']='Talebi Sil';
$hesklang['btn_delr']='Yanıtı Sil';
$hesklang['ernf']='Yanıt bulunamadı';
$hesklang['tns']='Talep bildirimleri tekrar gönderildi';
$hesklang['rns']='Yanıt bildirimleri tekrar gönderildi';
$hesklang['fname']='İsim';
$hesklang['export_selected']='Seçilen talepleri dışa aktar';
$hesklang['btn_export']='Excel için XML\'ye Aktar';
$hesklang['recaptcha']='reCAPTCHA';

// DO NOT CHANGE BELOW
if (!defined('IN_SCRIPT')) die('PHP sözdizimi Tamam!');